# 1. NumPy

In [2]:
import numpy as np

- NumPy is a Python library used for working with arrays.

- It also has functions for working in domain of linear algebra, fourier transform, and matrices.
- Numpy stands for Numerical python

### Application
- Linear Algebra
- Statistics
- Probability
- Trignometric Operations (sin,cos,tan,etc.....)
- Matrix
- Image Processing
- Logarithmic

## Array
- It is a collection of homogeneous datatypes
- ndarray ---> n-dimentional array
- Arrays are faster than list
- Numpy is written in c/c++ language(Partially in python)
- Arrays can be created with the help of tuples and list
- Supported Datatypes = int, float, complex, str

- In Python we have lists that serve the purpose of arrays, but they are slow to process.
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

- Arrays are very frequently used in data science, where speed and resources are very important.

### Why is NumPy Faster Than Lists?
- NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently. 
- This behavior is called locality of reference in computer science. 
- This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures. 


###### Note:- numpy arrays holds only one type of data type, any single type of another datatype value will change the whole dataset of array into differnent data type

### Creatign Dimensions
##### 1. 0 - d (Zero - Dimension Arrary)
   - collection of single data type 


##### 2. 1 - d (one - Dimension Arrary)
   - collection of zero dimension array


##### 3. 2 - d (Two - Dimension Arrary)
   - collection of two dimension array


##### 4. 3 - d (Three - Dimension Arrary)
   - collection of three dimension array

### 1. 0-D  (Zero - Dimension Arrary)

- 0 - dimanesion array is single element 

In [2]:
import numpy as np
arr1 = np.array(1000)
print(f"Array:- {arr1}")
print(f"dimensions of an array:- {arr1.ndim}")

print("<>"*50)

arr2 = np.array("yash dhakade")
print(f"Array:- {arr2}")
print(f"dimensions of string array:- {arr2.ndim}")

print("<>"*50)

arr = np.array(1,2,3)
print(f"Array:- {arr}")
print(f"dimensions of an array:- {arr.ndim}")

Array:- 1000
dimensions of an array:- 0
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Array:- yash dhakade
dimensions of string array:- 0
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>


TypeError: array() takes from 1 to 2 positional arguments but 3 were given

#### 1- d (one - dimension array)
- It is a collection of  0 - d array (in a list)

In [3]:
ar = np.array([1,2,3])
print(f"Array:- {ar}")
print(f"One Dimension array:- {ar.ndim}")
print(f"Shape of the array:- {ar.shape}")

Array:- [1 2 3]
One Dimension array:- 1
Shape of the array:- (3,)


#### 2 - d Arrary (2-d dimension array) 
- it is a collection of one dimension array

In [11]:
arr = np.array([[1,2,3], [10,20,30], [100,200,300]],float)

print(f"Array:- {arr}")
print(f"length of array:- {len(arr)}")
print(f"One Dimension array:- {arr.ndim}")
print(f"shape of array:- {arr.shape}\n")

print("<>"*50)

arr = np.array([[1,2,3]])
print(f"\nArray:- {arr}")
print(f"Length of an Array:- {len(arr)}")
print(f"Dimensions of an array are:- :- {arr.ndim}")
print(f"shape of an Array:- {arr.shape}")

Array:- [[  1.   2.   3.]
 [ 10.  20.  30.]
 [100. 200. 300.]]
length of array:- 3
One Dimension array:- 2
shape of array:- (3, 3)

<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

Array:- [[1 2 3]]
Length of an Array:- 1
Dimensions of an array are:- :- 2
shape of an Array:- (1, 3)


#### 3 - d Array (3 - d dimension array)
- it is a collection of two dimension array
- shape = (no. dim of array, rows, columns)
- OR (length of array, row, column)

In [14]:
arrr = np.array([[[1,4,7], [2,5,8]], [[3,6,9], [1,2,3]], [[4,5,6], [7,8,9]]],float)

print(f"Array: \n{arrr}")
print(f"length of an array:- {len(arrr)}")
print(f"dimensions of an array: {arrr.ndim}")
print(f"shape of an array: {arrr.shape}")
print(f"size of an array;- {arrr.size}")

Array: 
[[[1. 4. 7.]
  [2. 5. 8.]]

 [[3. 6. 9.]
  [1. 2. 3.]]

 [[4. 5. 6.]
  [7. 8. 9.]]]
length of an array:- 3
dimensions of an array: 3
shape of an array: (3, 2, 3)
size of an array;- 18


### 1. numpy.arr.ndim :-
- [int] Return the number of dimensions in arr.

### 2. numpy.arr.shape :- 
- it returns the shape of the array in tuple, 
- it returns (row, column) or
- it returns n-dimensions or Arrays and n-elements in it (n-dim, n-element)
- in two- dimension
    - shape = (rows, column)
- in three dimension
    - shape = (length array , rows, columns)


######  >>In 3 - dimension array
- arr.shape()
- it returns number of dimension (length of array, number of row's, number of columns )
- [dim, row, coloumn] oR [len(arr), row, column] or [number_of_arrays, row, column]

### 3. numpy.arr.size :-
- it returns the total number of elements present in each n - dimension array

# 1. Accesing array 

#### 1. Accessing array from 1-Dimention array

- we can access element from 1-D array as similar to python list

In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4])

print(arr[1])

2


#### 2.Accesing array from 2-Dimentional array
- we can access element from 2-D array by [Row, Column]

In [8]:
arr = np.array([[1,2,3,4,5],              ## first row
                [6,7,8,9,10]])            ## second row

print('2nd element on 1st row: ', arr[0, 1])
print('2nd element on 2st row: ', arr[1, 2])
print()
print('2nd element on 1st row: ', arr[0][1])
print('2nd element on 2st row: ', arr[1][2])

2nd element on 1st row:  2
2nd element on 2st row:  8

2nd element on 1st row:  2
2nd element on 2st row:  8


#### 3.Accessing elements from 3-Dimentional Array
###### arr[len(arry) ,row, Column]

In [10]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])
print()
print(arr[0][1][2])

6

6


#### data type conversion 

1. int   --> float, str
2. float --> int, str
3. int, float --> complex
4. complex --> float  Not Possible 

## 2. Converting n-dimension array

- ndmin = dimensions
- we can increase the dimension of the array by passing "ndmin" after passing an array


- syntax:- 
    - array = np.array([1,2,3],ndmin = 1/ 2/ 3)

 - array = np.array([1,2,3],ndmin = 1 /2 /3)

###### Note:- we can only convert our array upto 32-dimensions

In [14]:
arr = np.array([1,2,3,4])

dim_3 = np.array(arr,ndmin=3)
print(f"{dim_3.ndim}-d array is: {dim_3}")

3-d array is: [[[1 2 3 4]]]


## 3. reshape()
- The numpy.reshape() function shapes an array without changing the data of the array.
- Array which is reshaped without changing the data.

- syntax 
    - numpy.reshape(array, shape, order = 'C')
    
- to reshape the array 
    - 1. find the size of the array 
    - 2. then factorize the size of the array 
    - 3. that multiplication of the factors should be equal to size of the array

In [13]:
a = np.array([1,2,3,4,5,6])
print(a.size)

6


In [14]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

###### Combination of creating an array by its size of the factors
- 3,2
- 2,3

In [15]:
a.reshape(4,2)

ValueError: cannot reshape array of size 6 into shape (4,2)

###### Creating 3 dimensions array

In [25]:
## size = 12 - 6,2  4,3 
## combinations:-
###for two dimension array
# 1. 4,3 or 3,4
# 2. 6,2 or 2,6
# 3. 12,1 or 1,12

### for three dimension array
# 1. 2,3,2
# 2. 2,2,3

a3 = np.array([[1,2,3,4,5,6], [1,2,3,4,5,6]])
# a3.reshape(3,4)
a3.reshape(2,2,3)

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

### 4. np.append()
- this funciton will append the values into new array 
- syntax:- 
     - lis = np.append(array1,array2)

### 5. np.floor()
- this function will return the float array by removing numbers after decimals.
- syntax :- 
    - np.floor([1.2, 2.5, 3.6...etc...])

In [2]:
import numpy as np
np.floor([3.7,5.5,6.7,3.2,9.9,9.2])


array([3., 5., 6., 3., 9., 9.])

### 6. np.ceil()
- The numpy.ceil() is a mathematical function that returns the ceil of the elements of array. The ceil of the scalar x is the smallest integer i, such that i >= x
- syntax 
    - np.ceil([3.7,5.5,6.7,3.2,9.9,9.2])
- Ex.
    - 3.1 --> 4
    - 3.3 --> 4
    - 5.9 --> 6
    - 9.5 --> 10

In [4]:
np.ceil([3.7,5.5,6.7,3.2,9.9,9.2])

array([ 4.,  6.,  7.,  4., 10., 10.])

### 7. np.where()
- The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied. 
- syntax 
    - np.where(np.array([3.7,5.5,6.7,3.2,9.9,9.2]) condition))

In [9]:
np.where(np.array([3.7,5.5,6.7,3.2,9.9,9.2]) > 4)

(array([1, 2, 4, 5], dtype=int64),)

In [10]:
np.where(np.array([3.7,5.5,6.7,3.2,9.9,9.2]) < 4)

(array([0, 3], dtype=int64),)

### another method for accessing numpy array 
- we can access numpy by using for loop 

## 8. numpy.nditer()
- It is an efficient multidimensional iterator object using which it is possible to iterate over an array. Each element of an array is visited using Python’s standard Iterator interface.
- syntanx 
    - np.nditer(array)
- we can use this inside for loop as well
    - for i in np.nditer(array):
        - print(i)
###### Note:- using np.nditer() function, we don't need to use nested for loop

- he nditer class constructor has a flags parameter, which can take the following values


In [7]:
import numpy as np
arr = np.array([[[1,2,3,4,5,6],[7,8,9,10,11,12]],[[10,20,30,40,50,60],[70,80,90,100,110,120]]])
print(f"Size of an array: {arr.size}")

arr.reshape(2,2,3,2) #(4,6)

for i in np.nditer(arr):
    print(i)

Size of an array: 24
1
2
3
4
5
6
7
8
9
10
11
12
10
20
30
40
50
60
70
80
90
100
110
120


### 9. np.ndenumerate() 
- Multidimensional index iterator.

- Return an iterator yielding pairs of array coordinates and values.

In [12]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9], [10,11,12]]])

for i,j in np.ndenumerate(arr):
    print(i,j)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


### np.zeros()
- The numpy.zeros() function returns a new array of given shape and dtype, with zeros. 
- Syntax:
    - numpy.zeros(shape, dtype = float, order = 'C')
- we use  numpy.zeros() function for weight initialisation
- np.zeros(shape,dtype=float)
- Return an array of zeros only
- Weight Initialization
- Target column creation

In [13]:
np.zeros([4,4],int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

### np.ones()
- The np.ones() function returns a new array of given shape and dtype, with ones.
- syntax:
    - np.ones(shape, dtype=float, order="C")
- return an array of ones only

In [16]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9], [10,11,12]]])
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### np.arange( (start, stop,  step),dtype= (data type) )
- The arange() function is used to get evenly spaced values within a given interval.
- Values are generated within the half-open interval [start, stop]. 
- For integer arguments the function is equivalent to the Python built-in range function, but returns an ndarray rather than a list.

- sytax 
    - np.arange(start, stop, step, dtype)

In [2]:
import numpy as np
a = np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

## np.linspace()
- The linspace() function returns evenly spaced numbers over a specified interval [start, stop].
- The endpoint of the interval can optionally be excluded.


- Syntax 
    - np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [10]:
lin1 = np.linspace(1,20,num=10,endpoint=False, retstep=True)
print(lin1,"\n")
print("total numbers of equally spaced numbers are: ",len(lin1))

(array([ 1. ,  2.9,  4.8,  6.7,  8.6, 10.5, 12.4, 14.3, 16.2, 18.1]), 1.9) 

total numbers of equally spaced numbers are:  2


#### difference between np.linspace() and np.arange()
- in linspace() - we can spacify weather the endpoint should be include or exclude

-

- it np.arange() - it is use to get evenly spaced values within a given intervel

### np.eye()
- The eye() function is used to create a 2-D array with ones on the diagonal and zeros elsewhere. 
-
- syntax 
    - np.eye(shape, dtype)
    -
    - np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
    -
    - n = number of rows in output
    - m = Number of columns in the output. If None, defaults to N.
    - k = Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.
    
###### Note: This will not return an identity matrix because the rows and columns can not be same all the time 

In [8]:
eye = np.eye(4,6,k=0)
print(eye)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


### identity() 
- The identity array is a square array with ones on the main diagonal. The identity() function return the identity array.

- Syntax 
    - np.identity(n,dtype=None)
    - n = single value
###### Note:- need to specify only one number otherwise it will through an error

In [10]:
ar = np.identity(4,dtype=int)
ar

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

# random()
- This is use to generate random valued array
    - rand()
        - The random module's rand() method returns a random float between 0 and 1 .
        - 0 >= value < 1 (will be greater than equall to 0 but less than 1)
     
    - randint()
        - The randint() method takes a size parameter where you can specify the shape of an array.
        - and it returns the random value between specified range.
        - size parameter will return the random values from the specified range in specified shape
    -
    - randn()
    - ranf()

### 1. rand()
- this will generate a number between 0 and 1 upto total specifind number
- syntax
    - np.random.rand(d0, d1, ..., dn)

In [14]:
a = np.random.rand(5)
print(a)

[0.9946175  0.39777197 0.34443281 0.26372681 0.14368274]


In [15]:
a = np.random.rand(3,3)
print(a)

[[0.9146042  0.48819794 0.86632608]
 [0.03568089 0.00323734 0.45487999]
 [0.03772878 0.86196126 0.33611666]]


### 2. randint()
- this will return the random value from the specified range 
- size parameter will return the random values between specied range
- syntax 
    - np.random.randint(low, high, size=None)
        - size = shape of the array
        - low = start number
        - high = last number

In [21]:
rn1 = np.random.randint(15)
print(rn1)

7


In [22]:
rn2 = np.random.randint(1,5)
print(rn2)

2


In [23]:
rn3 = np.random.randint(1,20,size=(3,3,3))
print(rn3)

[[[10 11  3]
  [ 3 10 18]
  [ 3  2  9]]

 [[ 4 18  2]
  [14 13 16]
  [ 5  2 12]]

 [[ 4  2 18]
  [18 18 14]
  [19  2 16]]]


In [24]:
rn4 = np.random.randint(1,20,size=(3,3))
print(rn4)

[[ 9  9 13]
 [ 6  5  3]
 [ 9 19  6]]


### 3. randn()
- The numpy.random.randn() function creates an array of specified shape and fills it with random values as per standard normal distribution. 
If positive arguments are provided, randn generates an array of shape (d0, d1, …, dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1 (if any of the d_i are floats, they are first converted to integers by truncation). A single float randomly sampled from the distribution is returned if no argument is provided.
-
- it return the values which are normally distributed 
- mean 0 and variance 1
- Syntax
    - numpy.random.randn(d0, d1, ..., dn)

In [26]:
r = np.random.randn(15)
print(r)

[ 1.19843662 -0.19008343 -1.01557191 -0.94253109 -0.57696019 -0.03586292
 -0.32405147  0.63786337 -1.24980594  0.52520271 -2.33753121  1.25312656
 -0.13573347 -1.94929077  0.18161267]


### np.ranf()
- numpy.random.ranf() is one of the function for doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the half-open interval [0.0, 1.0).
- (0,1] --> 1 >= value > 0
- [0,1) --> 1 > value >= 0

In [27]:
r2 = np.random.ranf([5,2])
print(r2)

[[0.73882758 0.86798782]
 [0.3706973  0.34547639]
 [0.77708596 0.87923207]
 [0.38685004 0.376577  ]
 [0.2096433  0.62088076]]


### np.append()
- The append() function is used to append values to the end of an given array.
-syntax 
    - numpy.append(arr1, arr2, axis=None)

- axis = 0 --> Rows
- axis = 1 --> Col

###### Note:- If the dimensions of both the arrays are different then it will through an error if the axis is 1 or 0
###### Note:- Dimensions of an array should be same if axis is 1 or 0 
###### Note:- If the axis = None, then it will not through an error

In [28]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[[11,22,33,44,55]]])

arr3 = np.append(arr1, arr2,axis=None)

print(arr3)

[ 1  2  3  4  5 11 22 33 44 55]


In [29]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[[11,22,33,44,55]]])

arr3 = np.append(arr1, arr2,axis=1)

print(arr3)

AxisError: axis 1 is out of bounds for array of dimension 1

## np.sort()
- it will sort an array 

    - if axis = 0, it will sort the array by its column
    - if axis = 1, it will sort athe array by its row

- axis = 0 --> column 
- axis = 1 --> row

###### 1. sroting an array by axis = 1 (row)

In [19]:
arr = np.sort(np.array([[4, 2 ,5],[7, 9, 8],[3, 2, 1]]),axis=1)
arr

array([[2, 4, 5],
       [7, 8, 9],
       [1, 2, 3]])

###### 2. sroting an array by axis = 0 (column)

In [18]:
arr = np.sort(np.array([[2,4,5],[7,9,8],[3,2,1]]),axis=0)
arr

array([[2, 2, 1],
       [3, 4, 5],
       [7, 9, 8]])

## np.around()
- numpy.around(arr, decimals = 0, out = None) : This mathematical function helps user to evenly round array elements to the given number of decimals.
    - arr     - array
    - decimal -  [int, optional] Decimal places we want to round off.
- if don't give decimal number if after decimal the number is less than 5, it will return min. round vaule. if >5 it will return nearest max value

In [23]:
ar1 = np.around([1.7654321,6.7888978,2.4554332,5.667786],2)
ar1

array([1.77, 6.79, 2.46, 5.67])

In [24]:
ar2 = np.around([1.7654321,6.7888978,2.4554332,5.667786])
ar2

array([2., 7., 2., 6.])

In [25]:
np.around(2.43698)

2.0

In [26]:
np.around(2.53698)

3.0

# converting array to list
- first, find the array index
- then apply tolist()function
    - it is use to convert an array to a list
- arr[index].tolist()

- OR use list contructor to numpy.ndarray
    - list(numpy.ndarray)

In [34]:
strn  = "Machine Learning Is Amazing"

stn_array = np.array(list(strn.lower()))
arr_indices = np.where(stn_array == "a")
print(arr_indices)
print(type(arr_indices))

(array([ 1, 10, 20, 22], dtype=int64),)
<class 'tuple'>


In [33]:
arr_indices[0].tolist()

[1, 10, 20, 22]