In [1]:
import numpy as np

# 1. logarithmic functions

## 1. np.log(x)
- element wise natural log
- it returns log values

In [2]:
np.log([1,2,3,4,5,6])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947])

## 2. np.log2(x)
- it returns the values of log to the base 2

In [6]:
np.log2([1,2,3,4,5,6])

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 ])

## 3. np.log10(x)
- it returns the values of log to the base 10

In [7]:
np.log10([1,2,3,4,5,6])

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125])

## 4. np.log1p(x)

In [8]:
np.log1p([1,2,3,4,5,6])

array([0.69314718, 1.09861229, 1.38629436, 1.60943791, 1.79175947,
       1.94591015])

# 2. Linear Algebra

### 1. np.linalg.solve()
- this function will return the values of x and y 
-The Linear Algebra module of NumPy offers various methods to apply linear algebra on any numpy array.
- One can find:

    - rank, determinant, trace, etc. of an array.
    - eigen values of matrices
    - matrix and vector products (dot, inner, outer,etc. product), matrix exponentiation
    - solve linear or tensor equations and much more!

### 2. np.linalg.det()
- In NumPy, we can compute the determinant of the given square array with the help of numpy.
- linalg.det(). It will take the given square array as a parameter and return the determinant of 
that.
- Syntax 
    - np.linalg.det(array)

#### problem

- 3x + 5y + 10z = 20
- 4x + 7y + 13z = 30
- 2x + 17y + 3z = 40

- [3, 5, 10]
- [4, 7, 13]
- [2, 17, 3]
- [20, 30, 40]

In [11]:
eq1 = np.array([[3, 5, 10], [4, 7, 13], [2, 17, 3]])
eq2 = np.array([20, 30, 40])

linear_equestion = np.linalg.solve(eq1, eq2)

print(linear_equestion)

[ 45.  -1. -11.]


In [13]:
x = 45
y = -1
z = -11

print(3*x + 5*y + 10*z) 
print(4*x + 7*y + 13*z)
print(2*x + 17*y + 3*z)

20
30
40


### 3. inverse algebra
#### np.linalg.inv()
- The inverse of a matrix is just a reciprocal of the matrix as we do in normal arithmetic for a single number which is used to solve the equations to find the value of unknown variables. 
- The inverse of a matrix is that matrix which when multiplied with the original matrix will give as an identity matrix. 
- The inverse of a matrix exists only if the matrix is non-singular i.e., determinant should not be 0. 
- Using determinant and adjoint, we can easily find the inverse of a square matrix using below formula,

- The function numpy.linalg.inv() which is available in the python NumPy module is used to compute the inverse of a matrix. 
- Syntax
    - np.linalg.inv(x)

#### problem

In [15]:
inv_eq = np.array([[3, 5, 10], [4, 7, 13], [2, 17, 3]])
np.linalg.inv(inv_eq)

array([[-20. ,  15.5,  -0.5],
       [  1.4,  -1.1,   0.1],
       [  5.4,  -4.1,   0.1]])

## 3. copy array
- np.copy(array) allows us to copy a array.
- the change in the copied array will not reflect on original array
- Syntax
    - np.copy(array)
    -
    - array.copy()

In [17]:
eq1 = np.array([[3, 5, 10], [4, 7, 13], [2, 17, 3]])
print(eq1)

[[ 3  5 10]
 [ 4  7 13]
 [ 2 17  3]]


In [18]:
copy_eq = eq1.copy()

In [20]:
copy_eq[0][-1] = 1000

In [23]:
copy_eq  # change is only in copy_eq

array([[   3,    5, 1000],
       [   4,    7,   13],
       [   2,   17,    3]])

In [24]:
eq1 # change in original array not reflected

array([[ 3,  5, 10],
       [ 4,  7, 13],
       [ 2, 17,  3]])