# axis = 0 --> column
# axis = 1 --> row

In [26]:
list(range(1,15,2))

[1, 3, 5, 7, 9, 11, 13]

### np.arrange(start, stop, step)

In [1]:
import numpy as np

a = np.arange(1,15,2,dtype=int)
a

array([ 1,  3,  5,  7,  9, 11, 13])

In [42]:
a = np.arange(1,15,2/2)
print(a)
print(a[::-1])
print()
print("list of an array:- ",list(reversed(a)))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
[14. 13. 12. 11. 10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]

list of an array:-  [14.0, 13.0, 12.0, 11.0, 10.0, 9.0, 8.0, 7.0, 6.0, 5.0, 4.0, 3.0, 2.0, 1.0]


In [36]:
a1 = np.arange(15,1,-1)
a1

array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2])

### np.linspace()
- np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [51]:
lin = np.linspace(1,20)
print(lin,"\n")
print("total numbers of equally spaced are: ",len(lin))

[ 1.          1.3877551   1.7755102   2.16326531  2.55102041  2.93877551
  3.32653061  3.71428571  4.10204082  4.48979592  4.87755102  5.26530612
  5.65306122  6.04081633  6.42857143  6.81632653  7.20408163  7.59183673
  7.97959184  8.36734694  8.75510204  9.14285714  9.53061224  9.91836735
 10.30612245 10.69387755 11.08163265 11.46938776 11.85714286 12.24489796
 12.63265306 13.02040816 13.40816327 13.79591837 14.18367347 14.57142857
 14.95918367 15.34693878 15.73469388 16.12244898 16.51020408 16.89795918
 17.28571429 17.67346939 18.06122449 18.44897959 18.83673469 19.2244898
 19.6122449  20.        ] 

total numbers of equally spaced are:  50


In [55]:
lin1 = np.linspace(0, 20, num=10, endpoint=False, retstep=True)
print(lin1,"\n")
print("total numbers of equally spaced are: ",len(lin1))

(array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.]), 2.0) 

total numbers of equally spaced are:  2


In [60]:
evenly_spaced = np.linspace(0,20, num= 25, retstep=True)
print(evenly_spaced)

(array([ 0.        ,  0.83333333,  1.66666667,  2.5       ,  3.33333333,
        4.16666667,  5.        ,  5.83333333,  6.66666667,  7.5       ,
        8.33333333,  9.16666667, 10.        , 10.83333333, 11.66666667,
       12.5       , 13.33333333, 14.16666667, 15.        , 15.83333333,
       16.66666667, 17.5       , 18.33333333, 19.16666667, 20.        ]), 0.8333333333333334)


In [3]:
lin = np.linspace(0,50,num=30,retstep=True)
print(lin)

(array([ 0.        ,  1.72413793,  3.44827586,  5.17241379,  6.89655172,
        8.62068966, 10.34482759, 12.06896552, 13.79310345, 15.51724138,
       17.24137931, 18.96551724, 20.68965517, 22.4137931 , 24.13793103,
       25.86206897, 27.5862069 , 29.31034483, 31.03448276, 32.75862069,
       34.48275862, 36.20689655, 37.93103448, 39.65517241, 41.37931034,
       43.10344828, 44.82758621, 46.55172414, 48.27586207, 50.        ]), 1.7241379310344827)


In [14]:
lin = np.linspace(50,0, num=20, retstep=True)
print(lin)

(array([50.        , 47.36842105, 44.73684211, 42.10526316, 39.47368421,
       36.84210526, 34.21052632, 31.57894737, 28.94736842, 26.31578947,
       23.68421053, 21.05263158, 18.42105263, 15.78947368, 13.15789474,
       10.52631579,  7.89473684,  5.26315789,  2.63157895,  0.        ]), -2.6315789473684212)


In [10]:
50-47.5

2.5

In [11]:
47.5-45

2.5

In [13]:
 40. - 37.5

2.5

## eye(shape, dtype)

In [28]:
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
ar = np.eye(5,4)
ar

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [34]:
ar = np.eye(4,3, k=-1)
ar

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
ar = np.eye(3,5,dtype=int)
print(ar)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]


## identity()

In [39]:
ar = np.identity(3)
print(ar)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [40]:
ar = np.identity(3,2)

TypeError: Cannot interpret '2' as a data type

# random

### 1. rand()

In [43]:
rn = np.random.rand(10)
print(rn)

[0.27875525 0.02498534 0.01513156 0.13577076 0.45853758 0.11404124
 0.31664796 0.16370474 0.50556405 0.27083689]


In [45]:
r = np.random.rand(2,1,20)
print(r)

[[[0.06845188 0.75313198 0.98267325 0.45902869 0.95676029 0.20102852
   0.97092374 0.3155676  0.21980401 0.88398268 0.93526237 0.41070765
   0.12167965 0.34731147 0.35784403 0.47617144 0.96192036 0.92217931
   0.29866546 0.75644165]]

 [[0.49696854 0.7365291  0.493256   0.05899972 0.20917198 0.24474791
   0.13361668 0.89956692 0.08307227 0.50456238 0.30894707 0.1986204
   0.53278736 0.16632461 0.39452837 0.22588718 0.26523805 0.83401658
   0.01736854 0.2617145 ]]]


### random.randint()

In [61]:
arr = np.random.randint(10)
arr

6

In [79]:
ar = np.random.randint(1,10)
print(ar)

9


In [84]:
ar = np.random.randint(1,15,size=[3,3,4])
print(ar)

[[[14  2 12 12]
  [ 5 12 12  2]
  [ 7 10  6 10]]

 [[ 4 12 10  2]
  [12  2  6 11]
  [13  3  8 14]]

 [[ 1  7 12  2]
  [ 4  3  3 12]
  [ 2 14 11  7]]]


In [86]:
a = np.random.randint(0,20,size= (2,2,2))
print(a)

[[[ 9 16]
  [ 3  7]]

 [[ 1  8]
  [19  8]]]


In [90]:
squre = np.random.randint(1,20,size=(5,5))
squre

array([[ 3, 14,  9, 14,  7],
       [ 4, 10,  5, 16,  3],
       [11, 10, 14, 13,  5],
       [13, 13,  6, 13, 16],
       [18,  1, 15,  5,  5]])

### 3. randn()
- it returns the values which are normally distributed
- mean 0 and varience 1

In [91]:
r = np.random.randn(5)
r

array([ 0.6620394 , -1.07338461,  1.81828171,  1.98344363,  0.7813989 ])

In [108]:
ar = np.random.randn(5,5)
ar

array([[-0.2425116 , -1.27910568, -0.50213403, -0.03310773,  0.46973076],
       [ 1.78072086, -0.52302082,  1.65213093, -0.73326342, -0.4062294 ],
       [ 0.00996246, -0.21918491, -0.19187204, -0.11479776,  0.5625433 ],
       [ 2.2552123 , -0.20777915,  0.52786718,  1.03119209,  0.35967026],
       [ 1.17644165, -1.07484714,  0.01255328, -0.15401733,  0.06457658]])

In [109]:
print(len(ar))
for i in ar:
    print(i, "The size is: ",np.size(i))

5
[-0.2425116  -1.27910568 -0.50213403 -0.03310773  0.46973076] The size is:  5
[ 1.78072086 -0.52302082  1.65213093 -0.73326342 -0.4062294 ] The size is:  5
[ 0.00996246 -0.21918491 -0.19187204 -0.11479776  0.5625433 ] The size is:  5
[ 2.2552123  -0.20777915  0.52786718  1.03119209  0.35967026] The size is:  5
[ 1.17644165 -1.07484714  0.01255328 -0.15401733  0.06457658] The size is:  5


In [110]:
for i in np.nditer(ar):
    print(i)

-0.24251160291630258
-1.2791056759968695
-0.5021340285529575
-0.03310773313234392
0.46973075816477333
1.7807208628486189
-0.5230208191692022
1.6521309335503143
-0.7332634243565961
-0.40622939671740055
0.009962459911710336
-0.2191849107562699
-0.19187203914783685
-0.11479775820085701
0.56254329543766
2.2552123026495905
-0.2077791543566665
0.5278671816511352
1.031192086437841
0.3596702631081597
1.176441654406872
-1.0748471424204213
0.01255328272220987
-0.15401733276023324
0.06457658168150657


## Three Dimensions

In [4]:
arr = np.random.randn(3,3,3)
print(arr)
print(f"Dimensions of an array;- {np.ndim(arr)}")
print(f"length of an array:- {len(arr)}")
print(f"size of an array:- {np.size(arr)}")

[[[-1.76598323  0.38275941 -0.14655545]
  [ 0.2453827  -0.16935026 -2.21574124]
  [ 0.06257239  0.36861356  0.06012074]]

 [[ 0.27993187 -0.02210268  0.07216881]
  [-1.78401242 -0.89945555  1.84450408]
  [-0.39505333  0.42145072 -0.60327606]]

 [[-0.64702221  1.140452   -0.40427182]
  [-1.84972617 -0.55343918 -0.01634733]
  [-1.08139102 -1.36732521  1.06329998]]]
Dimensions of an array;- 3
length of an array:- 3
size of an array:- 27


In [3]:
for i in np.nditer(arr):
    print(i)

-1.722215104568594
1.2088367483034559
0.1454776062871773
-1.9505922753626879
0.8771581620423591
-1.5421750585175111
-0.5780928869604759
0.3931032251410268
0.418699809113353
-0.425777949950692
0.06961892999062294
-1.4110208764605705
0.3400778348541057
0.3577900120961334
-1.2973408847876955
0.4407330945493358
-1.01408699739082
-0.44331357727859927
0.4730287564299085
-0.8017834640915259
1.0591147325964145
0.37123500328542275
1.484106732178114
0.4840564997709862
1.632227343403569
-0.5335310157957931
1.279212123349484


## np.random.ranf()

In [8]:
ran = np.random.ranf(5)
ran

array([0.84420086, 0.42116705, 0.82019084, 0.74070312, 0.30152039])

In [21]:
# [0,0, 1.0)
ra = np.random.ranf((5,5))
print(ra)

[[0.60237974 0.88479749 0.6155852  0.32433495 0.59260378]
 [0.87811671 0.84124168 0.415975   0.36710595 0.8134948 ]
 [0.5066296  0.37310153 0.17275426 0.61789286 0.15239882]
 [0.8127833  0.04236134 0.97918911 0.63396914 0.04595546]
 [0.65889982 0.32011256 0.34415785 0.08847613 0.61471981]]


In [43]:
t = np.random.rand(5,5)

print(t)

[[0.97269469 0.89873603 0.52724855 0.45243788 0.06308878]
 [0.46052066 0.44974756 0.90059007 0.41395166 0.93135533]
 [0.02288397 0.93437722 0.90483602 0.20982028 0.77527096]
 [0.85194304 0.55476831 0.17329267 0.20600318 0.85178704]
 [0.8243856  0.52056094 0.97530056 0.67157714 0.15516211]]


In [23]:
r = np.random.ranf(5)
print(r)

[0.17952005 0.09957706 0.34597658 0.89579376 0.47556704]


In [40]:
r2 = np.random.ranf([5,2])
print(r2)

[[0.27415865 0.09211303]
 [0.07104729 0.16133728]
 [0.44335708 0.21838233]
 [0.93704378 0.96147037]
 [0.04892182 0.65966861]]


In [41]:
r2 = np.random.ranf([[5,2],[5,2]])
print(r2)

TypeError: 'list' object cannot be interpreted as an integer

In [26]:
rand1 = np.random.rand(5)
print(rand1)

[0.56790417 0.07164845 0.89291898 0.97344521 0.93043845]


In [36]:
rand2 = np.random.rand(3,5,2)
print(rand2)

[[[0.83020502 0.88781277]
  [0.10994947 0.27706936]
  [0.77387155 0.44990212]
  [0.22220121 0.89316032]
  [0.21999093 0.02670416]]

 [[0.49939729 0.35958801]
  [0.21665328 0.94797967]
  [0.47732207 0.94445563]
  [0.73439827 0.14385966]
  [0.12948935 0.96232401]]

 [[0.4161989  0.74450942]
  [0.69029843 0.44610066]
  [0.84564705 0.87844061]
  [0.40968481 0.53125899]
  [0.82146303 0.12695388]]]


## np.append()

In [57]:
ar = np.arange(1,10)
n1 = ar.reshape(3,3)
n2 = ar.reshape(3,2)

n3 = np.append(n1,n2)
print(n3)

ValueError: cannot reshape array of size 9 into shape (3,2)

In [58]:
ar = np.arange(1,10)
n1 = ar.reshape(3,3)
n2 = ar.reshape(3,3)

n3 = np.append(n1,n2)
print(n3)

[1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9]


In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([11,22,33,44,55])

arr3 = np.append(arr1, arr2)

print(arr3)

[ 1  2  3  4  5 11 22 33 44 55]


In [9]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[[11,22,33,44,55]]])

arr3 = np.append(arr1, arr2,axis=None)

print(arr3)

[ 1  2  3  4  5 11 22 33 44 55]


## np.sort()

In [11]:
s_nums = np.random.randint(1,20, size = 10)
print(s_nums)

[15  6  6  6  5 11  3 18 15  1]


In [12]:
sorted_nums = np.sort(s_nums)
print(sorted_nums)

[ 1  3  5  6  6  6 11 15 15 18]


In [14]:
s_nums1 = np.random.randint(1,20, size = (3,3))
print(s_nums1)

[[ 1  9 10]
 [11  3 18]
 [13 17 11]]


In [18]:
sorted_nums1 = np.sort(s_nums1,axis=0) # column
print(sorted_nums1)

[[ 1  3 10]
 [11  9 11]
 [13 17 18]]


In [19]:
sorted_nums2 = np.sort(s_nums1,axis=1) # row
print(sorted_nums2)

[[ 1  9 10]
 [ 3 11 18]
 [11 13 17]]


In [20]:
s = np.random.randint(1,10, size = (3,4))
s 

array([[6, 3, 2, 6],
       [6, 9, 2, 9],
       [8, 3, 2, 9]])

In [21]:
sorte_s = np.sort(s,axis=0) # column
print(sorte_s)

[[6 3 2 6]
 [6 3 2 9]
 [8 9 2 9]]


In [22]:
sorte_s1 = np.sort(s,axis=1) # row
print(sorte_s1)

[[2 3 6 6]
 [2 6 9 9]
 [2 3 8 9]]


## np.arange()

In [27]:
a = np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## np.linspace()

In [32]:
a = np.linspace(1,15,endpoint=False,num=10,retstep=True)
a

(array([ 1. ,  2.4,  3.8,  5.2,  6.6,  8. ,  9.4, 10.8, 12.2, 13.6]), 1.4)

In [39]:
dig = np.eye(3,5,k=-2)
print(dig)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
