In [1]:
import numpy as np

In [30]:
arr = np.arange(1, 20)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [29]:
x = np.linspace(1, 12,endpoint=False, num=10, retstep=True)
x

(array([ 1. ,  2.1,  3.2,  4.3,  5.4,  6.5,  7.6,  8.7,  9.8, 10.9]), 1.1)

# eye()

In [49]:
eye = np.eye(4,5,dtype=int)
eye

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

## identity

In [55]:
identity = np.identity(3,dtype=int)
identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## random()
  - rand() - range(start, stop) - 0,1> 0 and 1 not include (takes only 0 and 1 values not including 0  and 1)
  - randint()
  - randn()
  - ranf()

## rand()

In [168]:
r_ar = np.random.rand(1,20)
print(r_ar)

[[0.48369752 0.10236154 0.06053434 0.47288151 0.94042374 0.42915379
  0.24212688 0.72156009 0.84622394 0.1566894  0.67668316 0.50568064
  0.63446834 0.72746594 0.66011563 0.43412084 0.84573004 0.75040705
  0.82132667 0.10315715]]


In [109]:
r_int_arr = np.random.randint(1,11,size=[3,3])
r_int_arr

array([[4, 6, 1],
       [6, 5, 3],
       [4, 3, 9]])

## randn()

In [128]:
r_randf = np.random.randn(10)
r_randf

array([-0.4839913 ,  0.08155594, -0.61331529, -1.63307597, -2.39639861,
       -0.9020291 ,  0.56704398, -0.74956558, -0.93034218,  0.21171515])

## ranf()

In [172]:
rf = np.random.ranf(10)
print(rf)

[0.20320686 0.95764944 0.95820803 0.65654874 0.18702294 0.03153636
 0.06035409 0.44459431 0.82149199 0.15699984]


In [188]:
import pandas as pd

In [202]:
ar = {
    "randn": np.random.rand(10),
    "randint" : np.random.randint(1,10,size = 10)
}

In [203]:
data = pd.DataFrame(ar)
data

randn  randint
0  0.548979        9
1  0.966024        1
2  0.900598        9
3  0.608008        9
4  0.196778        7
5  0.565475        2
6  0.664626        6
7  0.548374        4
8  0.612117        6
9  0.548035        6

In [207]:
arr = np.random.randint(1,50,size=(3,3))
arr

array([[ 3, 36, 18],
       [ 8, 38,  6],
       [12, 31, 10]])

In [209]:
x = np.sort(arr,axis=1) # sort row
x

array([[ 3, 18, 36],
       [ 6,  8, 38],
       [10, 12, 31]])

In [210]:
x = np.sort(arr,axis=0) # sort column
x

array([[ 3, 31,  6],
       [ 8, 36, 10],
       [12, 38, 18]])

In [211]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([11,22,33,44,55])
new_arr = np.append(arr1,arr2)
new_arr

array([ 1,  2,  3,  4,  5, 11, 22, 33, 44, 55])