## numpy.reshape()

In [2]:
import numpy as np

a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
a.size

6

In [8]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [10]:
a.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [13]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a3 = np.array([[1,2,3,4,5,6], [1,2,3,4,5,6]])
print(len(a3))
print(a3.size)

2
12


In [26]:
a3.reshape(2,3,2)


array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]]])

In [18]:
a3.reshape(2,6)

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [20]:
a3.reshape(3,4)

array([[1, 2, 3, 4],
       [5, 6, 1, 2],
       [3, 4, 5, 6]])

In [36]:
a4 = np.array([[[1,2,3,4], [10,20,30,40]],[[11,22,33,44],[77,88,99,80]]])
print(len(a4))
print(a4.size)
## 16 
# 16,1 = 2,1,8
# 4,4 = 2,2,8
# 8,2 = 2,4,2

2
16


In [37]:
n =  16
for i in range(1,n+1):
    if n%i == 0:
        print(i,end=" ")

1 2 4 8 16 

In [33]:
a4.reshape(2,1,8)

array([[[ 1,  2,  3,  4, 10, 20, 30, 40]],

       [[11, 22, 33, 44, 77, 88, 99, 80]]])

In [45]:
a4.reshape(1,2,8)

array([[[ 1,  2,  3,  4, 10, 20, 30, 40],
        [11, 22, 33, 44, 77, 88, 99, 80]]])

In [46]:
a4.reshape(2,4,2)

array([[[ 1,  2],
        [ 3,  4],
        [10, 20],
        [30, 40]],

       [[11, 22],
        [33, 44],
        [77, 88],
        [99, 80]]])

In [48]:
a4.reshape(2,2,4)

array([[[ 1,  2,  3,  4],
        [10, 20, 30, 40]],

       [[11, 22, 33, 44],
        [77, 88, 99, 80]]])

In [49]:
a4.reshape(4,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[10, 20],
        [30, 40]],

       [[11, 22],
        [33, 44]],

       [[77, 88],
        [99, 80]]])

In [50]:
arr = np.array([1,2,3,4,5,6])

for i in arr:
    print(i)

1
2
3
4
5
6


In [55]:
a4 = np.array([[[1,2,3,4], [10,20,30,40]],[[11,22,33,44],[77,88,99,80]]])
for i in a4:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
10
20
30
40
11
22
33
44
77
88
99
80


In [3]:
import numpy as np
np.where(np.array([4, 5, 6, 7,8 ,9, 10]) %2==0 )

(array([0, 2, 4, 6], dtype=int64),)

In [8]:
arr = np.array([[1,2,3],[4,5,1],[2,3,4],[5,1,2]])

print(f"dimension of an array: {arr.ndim}")
print(f"length of an array: {len(arr)}")
print(f"shape of an array: {arr.shape}")
print(f"size of an array: {arr.size}")

dimension of an array: 2
length of an array: 4
shape of an array: (4, 3)
size of an array: 12


In [10]:
arr.reshape(2,6)

array([[1, 2, 3, 4, 5, 1],
       [2, 3, 4, 5, 1, 2]])

In [11]:
arr.reshape(3,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 1],
        [2, 3]],

       [[4, 5],
        [1, 2]]])

In [16]:
arr.reshape(3,4)

array([[1, 2, 3, 4],
       [5, 1, 2, 3],
       [4, 5, 1, 2]])

In [20]:
ar = np.array([[[1,2,3], [4,5,6]],[[7,8,9],[11,12,13]]])
for i in ar:
    for j in i:
        for k in j:
            if k % 2 == 0:
                print(k)

2
4
6
8
12


In [21]:
ar 

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]]])

In [23]:
for i in np.nditer(ar):
    print(i)

1
2
3
4
5
6
7
8
9
11
12
13


In [26]:
arrr = np.array([[[1,2,3], [4,5,6]],[[7,8,9],[11,12,13]]])
for i in np.nditer(arrr):
    print(i)

1
2
3
4
5
6
7
8
9
11
12
13


In [27]:
np.nditer(arrr)

In [35]:
ar1 = np.array([[[1,2,3], [4,5,6]],[[7,8,9],[11,12,13]]])
print(f"size of an array: {ar1.size}")
ar1.reshape(3,2,2)

size of an array: 12


array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 11],
        [12, 13]]])

In [36]:
for i in np.nditer(ar1):
    print(i)

1
2
3
4
5
6
7
8
9
11
12
13


In [46]:
a = np.arange(12)
a.reshape(3,4)

for i in np.nditer(a, order="F"):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [47]:
# Python program for
# iterating over array
# using particular order
 
import numpy as geek 
 
# creating an array using arrange 
# method
a = geek.arange(12) 
 
# shape array with 3 rows and 
# 4 columns 
a = a.reshape(3,4) 
 
print('Original array is:') 
print(a)
print()  
 
print('Modified array in C-style order:')
 
# iterating an array in a given
# order  
for x in geek.nditer(a, order = 'C'): 
    print(x)

Original array is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Modified array in C-style order:
0
1
2
3
4
5
6
7
8
9
10
11


In [58]:
import pandas as pd
data = {
"external_loop":"Causes values given to be one-dimensional arrays with multiple values instead of zero-dimensional array",
"c_index": "C_order index can be tracked",
"f_index": "Fortran_order index is tracked",
"multi-index": "Type of indexes with one per iteration can be tracked"
}

a = "a"
b = "b"
df  = pd.DataFrame(
print(df)

                                                                0
Causes values given to be one-dimensional array...  external_loop
C_order index can be tracked                              c_index
Fortran_order index is tracked                            f_index
Type of indexes with one per iteration can be t...    multi-index


In [72]:
data = {"Parameter" :  ["external_loop", "c_index", "f_index", "multi-index"],
        "DESCRIPTION": ["""Causes values given to be one-dimensional 
                        arrays with multiple values instead of zero-dimensional array""",
                       "C_order index can be tracked",
                       "Fortran_order index is tracked",
                       "Type of indexes with one per iteration can be tracked" ] }

df  = pd.DataFrame(data)
print(df)

       Parameter                                        DESCRIPTION
0  external_loop  Causes values given to be one-dimensional \n  ...
1        c_index                       C_order index can be tracked
2        f_index                     Fortran_order index is tracked
3    multi-index  Type of indexes with one per iteration can be ...


In [76]:
a = np.arange(12)
a.reshape(3,4)

for i in np.nditer(a, flags=["external_loop"]):
    print(i)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [78]:
for i in np.nditer(a, flags=["f_index"]):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [79]:
ar1 = np.array([[[1,2,3], [4,5,6]],[[7,8,9],[11,12,13]]])
for i in np.nditer(ar1, flags=["f_index"]):
    print(i)

1
2
3
4
5
6
7
8
9
11
12
13


In [81]:
ar1 = np.array([[[1,2,3], [4,5,6]],[[7,8,9],[11,12,13]]])
a = np.nditer(ar1)
print(next(a))
print(next(a))
print(next(a))
print(next(a))
print(next(a))
print(next(a))
print(next(a))

1
2
3
4
5
6
7


In [83]:
for i in enumerate([4,5,6,1,2,3]):
    print(i)

(0, 4)
(1, 5)
(2, 6)
(3, 1)
(4, 2)
(5, 3)


In [84]:
for i, j in enumerate([4,5,6,1,2,3]):
    print(i,j)

0 4
1 5
2 6
3 1
4 2
5 3


In [104]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9], [10,11,12]]])

for i,j in np.ndenumerate(arr):
    print(i,j)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


In [102]:
ad = np.arange(16)

ad.reshape(4,4)
for i, j in np.ndenumerate(ad):
    print(i,j)

(0,) 0
(1,) 1
(2,) 2
(3,) 3
(4,) 4
(5,) 5
(6,) 6
(7,) 7
(8,) 8
(9,) 9
(10,) 10
(11,) 11
(12,) 12
(13,) 13
(14,) 14
(15,) 15


In [109]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [110]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [115]:
r = np.zeros([4,4],int)
print(r)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [117]:
for i,j in np.ndenumerate(r):
    print(i,j)

(0, 0) 0
(0, 1) 0
(0, 2) 0
(0, 3) 0
(1, 0) 0
(1, 1) 0
(1, 2) 0
(1, 3) 0
(2, 0) 0
(2, 1) 0
(2, 2) 0
(2, 3) 0
(3, 0) 0
(3, 1) 0
(3, 2) 0
(3, 3) 0


## numpy.ones()

In [119]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9], [10,11,12]]])
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [122]:
np.ones([3,4],dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [124]:
import pandas as pd

df = pd.DataFrame({
    "Zeros": np.zeros([3,3],dtype=int),
    "Ones" : np.zeros([3,3],dtype=int)
})

ValueError: Per-column arrays must each be 1-dimensional

In [135]:
df = pd.DataFrame({
    "Zeros": np.zeros(5,dtype=int),
    "Ones" : np.ones(5,dtype=int)
})
print(df)

   Zeros  Ones
0      0     1
1      0     1
2      0     1
3      0     1
4      0     1
