### indexign and sliceing

In [1]:
lis = [1,2,3,4,5]
print(lis[0])
print(lis[3])
print(lis[-1])
print(lis[-3])

1
4
5
3


In [2]:
print(lis[2:4])

[3, 4]


In [3]:
print(lis[-2:-4])

[]


In [4]:
print(lis[-2:-4:-1]) # OR
print(lis[-4:-2])

[4, 3]
[2, 3]


In [5]:
import numpy as np

### slicing on 0-d array
- indices are not possible

In [6]:
a = np.array(1000)
print(a[0])

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

### slicing on 1-d array

In [7]:
ar = np.array([1,2,3])
print(f"dimension of an array: {ar.ndim}")

print(ar[0])
print(ar[1])
print(ar[2])
print(ar[-1])
print(ar[-1:-3:-1])
print(ar[-3:-1])

dimension of an array: 1
1
2
3
3
[3 2]
[1 2]


### slicing on 2-d array

In [8]:
arr = np.array([[1,2,3],[4,5,6]])
print(f"dimensions of an array:- {arr.ndim}")

print("array number 0>",arr[0])
print(arr[0, 1])
print(arr[0, -1])
print(arr[0, 0:])
print(arr[0, 1:])

print("<>"*20)

print("array number 1>",arr[1])
print(arr[1,0])
print(arr[1,-1])
print(arr[1,2:])
print(arr[1,-1:-3:-1])

dimensions of an array:- 2
array number 0> [1 2 3]
2
3
[1 2 3]
[2 3]
<><><><><><><><><><><><><><><><><><><><>
array number 1> [4 5 6]
4
6
[6]
[6 5]


In [9]:
arr = np.array([[1,2,3,4,5,6],[10,20,30,40,50,60],[100,200,300,400,500,600]])
print("dimension of an array:-",arr.ndim)

print(arr[2])
print(arr[2,2:])
print(arr[2,-1:-6:-1])
print(arr[0,-6:-1])
print(arr[1,-1])
print(arr[2,2])

print("<>"*20)

print(arr[2][2])

print(arr[2])
print(arr[2][2:])

print(arr[2][-1:-6:-1])
print(arr[2][-1])
print(arr[0][-1])
print(arr[0][3])
print(arr[1][2:])

dimension of an array:- 2
[100 200 300 400 500 600]
[300 400 500 600]
[600 500 400 300 200]
[1 2 3 4 5]
60
300
<><><><><><><><><><><><><><><><><><><><>
300
[100 200 300 400 500 600]
[300 400 500 600]
[600 500 400 300 200]
600
6
4
[30 40 50 60]


### slicing in 3-d array

In [10]:
arr = np.array([[[1,2,3], [10,20,30]],           ## 0
                [[100,200,300], [10,40,70]]])    ## 1
print("Array: \n",arr)
print("\ndimension of an array:-",arr.ndim)
print()
print(arr[1][0])
print(arr[1][0][1])
print(arr[1][1][1])
print(arr[1][1][0])
print(arr[1][1])
print(arr[1][1][1])
print(arr[1][1][0])

print("<>"*20)

print(arr[1,1,1])
print(arr[1,1,2])
print(arr[0,0])
print(arr[0,0,2])
print(arr[0,1,-1])

Array: 
 [[[  1   2   3]
  [ 10  20  30]]

 [[100 200 300]
  [ 10  40  70]]]

dimension of an array:- 3

[100 200 300]
200
40
10
[10 40 70]
40
10
<><><><><><><><><><><><><><><><><><><><>
40
70
[1 2 3]
3
30


In [11]:
arr = np.array([[[1,2,3], [10,20,30]],           ## 0
                [[100,200,300], [10,40,70]]])    ## 1
print("Array: \n",arr)
print("\ndimension of an array:-",arr.ndim)

print(arr[0][0][1:])
print(arr[0][0][:2])
print(arr[0,0,1:])

Array: 
 [[[  1   2   3]
  [ 10  20  30]]

 [[100 200 300]
  [ 10  40  70]]]

dimension of an array:- 3
[2 3]
[1 2]
[2 3]


## 2 - d array

In [12]:
arr = np.array([[1,2,3,4,5],[10,20,30,40,50],[100,200,300,400,500]],int)
print(f"Array --> \n{arr}")
print(f"Number of dimensions = {arr.ndim}")
print(f"Length --> {len(arr)}")
print(f"Shape of an array --> {arr.shape}")

Array --> 
[[  1   2   3   4   5]
 [ 10  20  30  40  50]
 [100 200 300 400 500]]
Number of dimensions = 2
Length --> 3
Shape of an array --> (3, 5)


In [13]:
print(arr[0: , 0:2])

[[  1   2]
 [ 10  20]
 [100 200]]


In [14]:
print(arr[1:3, -2:])

[[ 40  50]
 [400 500]]


In [15]:
print(arr[:, 0:3])

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]]


In [16]:
print(arr[:])

[[  1   2   3   4   5]
 [ 10  20  30  40  50]
 [100 200 300 400 500]]


### 3 - d Array

In [17]:
arr1 = np.array([[[1,2,3,4], [5,6,7,8]], [[9,10,11,12], [1,4,7,8]], [[5,2,0,9], [6,3,9,1]]]) ## 1
print("dimension of arry: \n",arr1)

dimension of arry: 
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [ 1  4  7  8]]

 [[ 5  2  0  9]
  [ 6  3  9  1]]]


In [18]:
print(arr1[0:, 0:, 0:-1])

[[[ 1  2  3]
  [ 5  6  7]]

 [[ 9 10 11]
  [ 1  4  7]]

 [[ 5  2  0]
  [ 6  3  9]]]


In [19]:
print(arr1[:, :, 1:-1])

[[[ 2  3]
  [ 6  7]]

 [[10 11]
  [ 4  7]]

 [[ 2  0]
  [ 3  9]]]


In [20]:
print(arr1[:-1, :, 0:2])

[[[ 1  2]
  [ 5  6]]

 [[ 9 10]
  [ 1  4]]]


In [21]:
arr1[:-1, 1:, 0:2]

array([[[5, 6]],

       [[1, 4]]])

In [22]:
arr1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [ 1,  4,  7,  8]],

       [[ 5,  2,  0,  9],
        [ 6,  3,  9,  1]]])

In [23]:
arr1[0:, 0:-1, 1:-1]

array([[[ 2,  3]],

       [[10, 11]],

       [[ 2,  0]]])

In [24]:
arr1[0:, 0:-1, 1:4]   ## [dimension control, row control, column control]

array([[[ 2,  3,  4]],

       [[10, 11, 12]],

       [[ 2,  0,  9]]])

In [25]:
arr1 = np.array([[[1,2,3,4], [5,6,7,8]], [[9,10,11,12], [1,4,7,8]], [[5,2,0,9], [6,3,9,1]]]) ## 1
print("dimension of arry: \n",arr1)

dimension of arry: 
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [ 1  4  7  8]]

 [[ 5  2  0  9]
  [ 6  3  9  1]]]


In [31]:
arr1[0:2,:, 0:2]

array([[[ 1,  2],
        [ 5,  6]],

       [[ 9, 10],
        [ 1,  4]]])