In [20]:
import numpy as np
import pandas as pd

In [3]:
ar = np.linspace(0,9,num=15)
ar

array([0.        , 0.64285714, 1.28571429, 1.92857143, 2.57142857,
       3.21428571, 3.85714286, 4.5       , 5.14285714, 5.78571429,
       6.42857143, 7.07142857, 7.71428571, 8.35714286, 9.        ])

In [4]:
nw_ar = np.array(ar,ndmin=3)

In [5]:
nw_ar

array([[[0.        , 0.64285714, 1.28571429, 1.92857143, 2.57142857,
         3.21428571, 3.85714286, 4.5       , 5.14285714, 5.78571429,
         6.42857143, 7.07142857, 7.71428571, 8.35714286, 9.        ]]])

In [6]:
ar = np.array([[[10, 20], [30, 40]], [[5, 10], [25, 35]]])
ar

array([[[10, 20],
        [30, 40]],

       [[ 5, 10],
        [25, 35]]])

In [10]:
ar[1,0][0] = 0

In [11]:
ar

array([[[10, 20],
        [30, 40]],

       [[ 0, 10],
        [25, 35]]])

In [12]:
ar.size

8

In [18]:
ar.reshape(8)

array([10, 20, 30, 40,  0, 10, 25, 35])

In [19]:
df = { 'color' : ['red', 'blue', 'green', 'yellow', 'blue', 'red', 'white', 'green'],
      'box' : [ 2, 5, 3, 8, 1, 7, 8, 3] , 
        'region' : [ 'north', 'south', 'east', 'south', 'south', 'north', 'NE', 'east']
     }

In [21]:
data = pd.DataFrame(df)

In [22]:
data

color  box region
0     red    2  north
1    blue    5  south
2   green    3   east
3  yellow    8  south
4    blue    1  south
5     red    7  north
6   white    8     NE
7   green    3   east

In [23]:
data.sort_values(["box"])

color  box region
4    blue    1  south
0     red    2  north
2   green    3   east
7   green    3   east
1    blue    5  south
5     red    7  north
3  yellow    8  south
6   white    8     NE

In [24]:
data["color"].unique()

array(['red', 'blue', 'green', 'yellow', 'white'], dtype=object)