## Iterator and Generator
- iterator is an object, which impliments iterator protocall
- it has only two functions 
- (__iter__) and (__next__)

In [1]:
st = "Python"
obj = iter(st)

In [4]:
print(next(obj))
print(next(obj))
print(next(obj))
print(next(obj))
print(next(obj))

StopIteration: 

In [7]:
lis = [1,2,3,4,5,6]

ob1 = iter(lis)

print(next(ob1))
print(next(ob1))
print(next(ob1))
print(next(ob1))
print(next(ob1))
print(next(ob1))
print(next(ob1))

1
2
3
4
5
6


StopIteration: 

In [16]:
nums = iter(range(1,5))
print(next(nums))
print(next(nums))
print(next(nums))
print(next(nums))
print(next(nums))

1
2
3
4


StopIteration: 

### Generator

In [13]:
def Range():
    for i in range(1,10):
        yield i 
        
Range()
for i in Range():
    print(i)

1
2
3
4
5
6
7
8
9


In [1]:
import pandas as pd
import numpy as np

### Create dataframe one col is number from 1-50 , then second col square of that no and third col is cube of that no.

In [4]:
data = pd.DataFrame()
data

Empty DataFrame
Columns: []
Index: []

In [5]:
data["col1"] = np.arange(1,51)

In [7]:
data["col2"] = data["col1"]**2

In [8]:
data["col3"] = data["col1"]**3

In [9]:
data

col1  col2    col3
0      1     1       1
1      2     4       8
2      3     9      27
3      4    16      64
4      5    25     125
5      6    36     216
6      7    49     343
7      8    64     512
8      9    81     729
9     10   100    1000
10    11   121    1331
11    12   144    1728
12    13   169    2197
13    14   196    2744
14    15   225    3375
15    16   256    4096
16    17   289    4913
17    18   324    5832
18    19   361    6859
19    20   400    8000
20    21   441    9261
21    22   484   10648
22    23   529   12167
23    24   576   13824
24    25   625   15625
25    26   676   17576
26    27   729   19683
27    28   784   21952
28    29   841   24389
29    30   900   27000
30    31   961   29791
31    32  1024   32768
32    33  1089   35937
33    34  1156   39304
34    35  1225   42875
35    36  1296   46656
36    37  1369   50653
37    38  1444   54872
38    39  1521   59319
39    40  1600   64000
40    41  1681   68921
41    42  1764   74088
42    43  1849   79507
43    44  1936   85184
44    45  2025   91125
45    46  2116   97336
46    47  2209  103823
47    48  2304  110592
48    49  2401  117649
49    50  2500  125000

In [13]:
arr = np.array([1,2,3],ndmin=3)
arr.ndim

3

In [15]:
add = 0
for i in np.arange(1,6):
    add += i
print(add)

15


In [19]:
ar = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print("Original array: \n",ar)
print("reversed column array: \n",ar[0:, ::-1])
print("reversed Row array: \n",ar[::-1, 0:])

Original array: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
reversed column array: 
 [[2 1 0]
 [5 4 3]
 [8 7 6]]
reversed Row array: 
 [[6 7 8]
 [3 4 5]
 [0 1 2]]


In [21]:
ar = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
ar[0:, 0:1]

array([[0],
       [3],
       [6]])

In [36]:
ar[1:2, 1]

array([4])

In [37]:
ar[0:, 2:3]

array([[2],
       [5],
       [8]])

In [38]:
ar[0:, 1:2]

array([[1],
       [4],
       [7]])

In [39]:
ar[0]

array([0, 1, 2])

In [40]:
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
ar = np.array([[1, 2, 0], [4, 3, 5], [8, 6, 7]])
display(ar)
ar.sort(axis=1)
display(ar)

array([[1, 2, 0],
       [4, 3, 5],
       [8, 6, 7]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
data["col1"]

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
23    24
24    25
25    26
26    27
27    28
28    29
29    30
30    31
31    32
32    33
33    34
34    35
35    36
36    37
37    38
38    39
39    40
40    41
41    42
42    43
43    44
44    45
45    46
46    47
47    48
48    49
49    50
Name: col1, dtype: int32