In [1]:
import numpy as np

In [8]:
nums = np.array([1,2,3,4,5,5.5],dtype="int64")

In [10]:
nums

array([1, 2, 3, 4, 5, 5], dtype=int64)

In [9]:
nums.dtype

dtype('int64')

In [12]:
alph = np.array(list("ABCDEF"))

In [13]:
alph

array(['A', 'B', 'C', 'D', 'E', 'F'], dtype='<U1')

In [28]:
alph.tolist()[::-1]

['F', 'E', 'D', 'C', 'B', 'A']

In [32]:
alph.tolist()[0:-1]

['A', 'B', 'C', 'D', 'E']

In [52]:
## 0-d Array

In [53]:
arr1 = np.array(100)
print(f"shape of an array: {arr1.shape}")
print(f"size of an array: {arr1.size}")
print(f"data type of an array: {arr1.dtype}")
print(f"dimension of an array: {arr1.ndim}-dimensions")
# print(f"length of an array: {len(arr1)}")

shape of an array: ()
size of an array: 1
data type of an array: int32
dimension of an array: 0-dimensions


In [54]:
## 1-d Array

In [62]:
arr2 = np.array([1,2,3])
print(f"shape of an array: {arr2.shape}")
print(f"size of an array: {arr2.size}")
print(f"data type of an array: {arr2.dtype}")
print(f"dimension of an array: {arr2.ndim}-dimensions")
print(f"length of an array: {len(arr2)}")

shape of an array: (3,)
size of an array: 3
data type of an array: int32
dimension of an array: 1-dimensions
length of an array: 3


In [63]:
arr3 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print(f"Array:- \n{arr3}")
print(f"shape of an array: {arr3.shape}")
print(f"size of an array: {arr3.size}")
print(f"data type of an array: {arr3.dtype}")
print(f"dimension of an array: {arr3.ndim}-dimensions")
print(f"length of an array: {len(arr3)}")

Array:- 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape of an array: (3, 3)
size of an array: 9
data type of an array: int32
dimension of an array: 2-dimensions
length of an array: 3


In [65]:
arr4 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [11,12,13]]])
print(f"Array:- \n{arr4}")
print(f"shape of an array: {arr4.shape}")
print(f"size of an array: {arr4.size}")
print(f"data type of an array: {arr4.dtype}")
print(f"dimension of an array: {arr4.ndim}-dimensions")
print(f"length of an array: {len(arr4)}")

Array:- 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 13]]]
shape of an array: (2, 2, 3)
size of an array: 12
data type of an array: int32
dimension of an array: 3-dimensions
length of an array: 2


In [81]:
arr = np.array(100, ndmin=3)
arr

array([[[100]]])

In [82]:
arr4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]]])

In [90]:
arr4[0][0][1]

2

In [91]:
arr4[0,1,-1]

6

In [92]:
arr4[1,1,-1]

13

In [93]:
arr4[1,0,1]

8

In [94]:
arr5 = np.array([[1,2,3,4,5],[10,20,30,40,50],[100,200,300,400,500]],int)
arr5

array([[  1,   2,   3,   4,   5],
       [ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [98]:
arr5[-1,1]

200

In [99]:
arr5[0,3]

4

In [100]:
arr5[2,-1]

500

In [101]:
arr4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]]])

In [111]:
arr4[0:,0:,-1]

array([[ 3,  6],
       [ 9, 13]])

In [116]:
arr4[0:,0:,1 ]

array([[ 2,  5],
       [ 8, 12]])

In [119]:
arr4[1:, 0:, 1]

array([[ 8, 12]])

In [120]:
arr5

array([[  1,   2,   3,   4,   5],
       [ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [121]:
arr5[0:,0]

array([  1,  10, 100])

In [126]:
arr5[0:,-1]

array([  5,  50, 500])

In [127]:
arr5[0:,2]

array([  3,  30, 300])

In [129]:
arr5[1,2]

30

In [132]:
arr5[2,2]

300

In [134]:
arr4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]]])

In [135]:
arr4.size
# 6,2
# 3,2,2 or 2,2,3
# 3,4 or 3,2,2

12

In [136]:
arr4.shape

(2, 2, 3)

In [137]:
arr4.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 11],
        [12, 13]]])

In [138]:
arr5

array([[  1,   2,   3,   4,   5],
       [ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [139]:
arr5.size

15

In [140]:
arr5.reshape(15,1)

array([[  1],
       [  2],
       [  3],
       [  4],
       [  5],
       [ 10],
       [ 20],
       [ 30],
       [ 40],
       [ 50],
       [100],
       [200],
       [300],
       [400],
       [500]])

In [141]:
arr5.reshape(1,15)

array([[  1,   2,   3,   4,   5,  10,  20,  30,  40,  50, 100, 200, 300,
        400, 500]])

In [142]:
arr4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]]])

In [147]:
arr4[:,:,2:3]

array([[[ 3],
        [ 6]],

       [[ 9],
        [13]]])

In [148]:
arr4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]]])

In [149]:
nw_arr = np.append(np.array([1,2,3]),arr4)

In [150]:
nw_arr

array([ 1,  2,  3,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [153]:
nw_arr1 = np.append(arr4, np.array(100))

In [154]:
nw_arr1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  11,  12,  13, 100])

In [162]:

nw_arr1 = np.append(arr4, np.array(100,ndmin=4))

In [163]:
nw_arr1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  11,  12,  13, 100])

In [171]:

nw_arr1 = np.append(arr4,np.array(5000,ndmin=4))

In [172]:
nw_arr1

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   11,   12,
         13, 5000])

In [185]:
f_value = np.array([1.5,5.5,3.6,12.2,3.2,6.2])

In [188]:
np.floor(f_value)

array([ 1.,  5.,  3., 12.,  3.,  6.])

In [189]:
np.ceil(f_value)

array([ 2.,  6.,  4., 13.,  4.,  7.])

In [193]:
around_val = np.around(f_value)
around_val

array([ 2.,  6.,  4., 12.,  3.,  6.])

In [194]:
np.where(around_val > 5)

(array([1, 3, 5], dtype=int64),)

In [199]:
np.where(around_val % 2 == 0)[0].tolist()

[0, 1, 2, 3, 5]

In [200]:
arr4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]]])

In [201]:
for i in arr4:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
11
12
13


In [202]:
for i in np.nditer(arr4):
    print(i)

1
2
3
4
5
6
7
8
9
11
12
13


In [204]:
for i,j in np.ndenumerate(arr4):
    print(i,j)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 11
(1, 1, 1) 12
(1, 1, 2) 13


In [209]:
z_ar = np.zeros(10,dtype=int)
z_ar

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [210]:
z_mt = np.zeros([3,3],dtype=int)
z_mt

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [212]:
one_ar = np.ones([3,3])
one_ar

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [214]:
one_mt = np.ones(10,int)
one_mt

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [219]:
spaced_val = np.linspace(1, 15, num=10,endpoint=False, retstep=True)
spaced_val

(array([ 1. ,  2.4,  3.8,  5.2,  6.6,  8. ,  9.4, 10.8, 12.2, 13.6]), 1.4)

In [231]:
eye = np.eye(3,5,k=2,dtype=int)
eye

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [234]:
identy= np.identity(3,dtype=int)
identy

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [251]:
rand = np.random.rand()  
rand

0.05585214941455219

In [262]:
randint = np.random.randint(1,15,size=[3,3])
randint

array([[13,  9,  5],
       [ 3,  5,  3],
       [10, 10,  5]])

In [266]:
randn = np.random.randn(5) # mean 0 and variance 1
randn

array([ 0.59884324, -0.22026296, -0.07083474,  0.23591099, -0.22485722])

In [290]:
ranf = np.random.ranf(5)
ranf

array([0.46145467, 0.84314843, 0.73814889, 0.62905192, 0.35659695])

In [291]:
arr4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]]])

In [298]:
ar1 = np.array([[[ 1,  2,  3], [ 4,  5,  6]], [[ 7,  8,  9], [11, 12, 13]]])
ar2 = np.array([[[11, 22, 33], [44, 55, 66]], [[77, 88, 99], [100, 200,300]]])

ar3 = np.append(ar1,ar2)

In [299]:
ar3

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  11,  12,  13,  11,
        22,  33,  44,  55,  66,  77,  88,  99, 100, 200, 300])

In [302]:
ar4 = np.append(ar1, ar2,axis=1)
ar4

array([[[  1,   2,   3],
        [  4,   5,   6],
        [ 11,  22,  33],
        [ 44,  55,  66]],

       [[  7,   8,   9],
        [ 11,  12,  13],
        [ 77,  88,  99],
        [100, 200, 300]]])

In [303]:
ar4 = np.append(ar1, ar2,axis=0)
ar4

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 11,  12,  13]],

       [[ 11,  22,  33],
        [ 44,  55,  66]],

       [[ 77,  88,  99],
        [100, 200, 300]]])

In [307]:
ar2.sort()
ar2

array([[[ 11,  22,  33],
        [ 44,  55,  66]],

       [[ 77,  88,  99],
        [100, 200, 300]]])

In [308]:
radom_ar = np.random.randint(1,15,size=5)

In [310]:
radom_ar.sort()

In [311]:
radom_ar

array([ 2,  3,  7,  7, 11])

In [312]:
radom_ar = np.random.randint(1,15,size=[3,3])

In [313]:
radom_ar

array([[ 3, 14,  7],
       [ 9, 12,  2],
       [ 3,  5,  9]])

In [314]:
radom_ar.sort(axis=1)

In [315]:
radom_ar

array([[ 3,  7, 14],
       [ 2,  9, 12],
       [ 3,  5,  9]])

In [316]:
radom_ar.sort(axis=0)
radom_ar

array([[ 2,  5,  9],
       [ 3,  7, 12],
       [ 3,  9, 14]])

In [317]:
np.full(shape=[3,3], fill_value=5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [325]:
ar2.itemsize

4

In [327]:
radom_ar.itemsize

4