In [1]:
def HelloFunc(func):
    print("Hello 1")
    
    def Inner_func():
        print("Inner function 2")
        func()
        return "Inner func"
    return Inner_func

In [2]:
@HelloFunc
def print_data():
    print("THis is end")
print_data()

Hello 1
Inner function 2
THis is end


'Inner func'

In [3]:
# obj = HelloFunc(print_data)
# obj()

In [4]:
def Division(func):
    print("in Divsion Func")
    
    def Inner_Division(a,b):
        if a < b:
            a,b = b,a
        else:
            func(a,b)
        return func(a,b)
    
    return Inner_Division

In [5]:
@Division
def Div(a,b):
    return a/b

Div(2,10)

in Divsion Func


5.0

In [6]:
Div(10,2)

5.0

In [7]:
Div(5,10)

2.0

In [8]:
Div(10,5)

2.0

In [9]:
Div(2,10)

5.0

In [10]:
Div(10,2)

5.0

## iterators

In [2]:
class Range():
    def __init__(self,start,last):
        self.start = start
        self.last = last
        
    def __iter__(self):
        self.start
    
    def __next__(self):
        if self.start < self.last:
            self.start += 1
            var = self.start
            return var
        else:
            raise StopIteration
    
    
Range = Range(1,5)
print(Range.__next__())
print(Range.__next__())
print(Range.__next__())
print(Range.__next__())
print(Range.__next__())

2
3
4
5


StopIteration: 

In [14]:
print(next(Range))
print(next(Range))

StopIteration: 

In [15]:
def sqr(nums):
    for i in nums:
        sq = i ** 2
        yield sq
        
x = sqr([1,2,3,4,5,6])

for i in x:
    print(i)

1
4
9
16
25
36


In [16]:
import numpy as np

In [ ]:
3x + 5y + 10z = 20
4x + 7y + 13z = 30
2x + 17y + 3z = 40

In [19]:
arr1 = np.array([[[3,5,10],[4,7,13],[2,17,3]]])
print(f"Array1 --> \n{arr1}")
arr2 = np.array([20,30,40])
print(f"Array2 --> \n{arr2}")

Array1 --> 
[[[ 3  5 10]
  [ 4  7 13]
  [ 2 17  3]]]
Array2 --> 
[20 30 40]
