In [1]:
import numpy as np

In [4]:
# dir(np)

In [22]:
log = np.log(5)
log

1.6094379124341003

In [21]:
np.log10(5)

0.6989700043360189

In [20]:
np.log2(5)

2.321928094887362

In [23]:
np.log1p(5)

1.791759469228055

In [24]:
ar = np.array([1,2,3,4,5,6])
np.log2(ar)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 ])

In [25]:
ar = np.array([1,2,3,4,5,6])
np.log10(ar)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125])

In [32]:
ar = np.array([1,2,3,4,5,6])
np.log(ar)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947])

In [33]:
np.log(0)

C:\Users\yashd\AppData\Local\Temp\ipykernel_16592\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [36]:
np.tan(np.log(20))

-0.1469036647664041

In [40]:
np.tan(np.log(90))

4.63305249133717

In [38]:
np.tan(90)

-1.995200412208242

In [ ]:
3x + 2y = 15
4x + 6y = 30

In [43]:
arr1 = np.array([[3,2],[4,6]])
arr2 = np.array([15,30])
algeb = np.linalg.solve(arr1, arr2)
print(algeb)

[3. 3.]


In [45]:
x = 3
y = 3

print(3*x + 2*y )
print(4*x + 6*y )

15
30


In [47]:
# 3x + 5y + 10z = 20
# 4x + 7y + 13z = 30
# 2x + 17y + 3z = 40

arr1 = np.array([[3,5,10],[4,7,13],[2,17,3]])
arr2 = np.array([20,30,40])
algeb = np.linalg.solve(arr1, arr2)
print(algeb)

[ 45.  -1. -11.]


In [49]:
x = 45
y = -1
z = -11

print(3*x + 5*y + 10*z)
print(4*x + 7*y + 13*z)
print(2*x + 17*y + 3*z)

20
30
40


In [51]:
arr1 = np.array([[3,5,10],[4,7,13],[2,17,3]])
print(arr1)

[[ 3  5 10]
 [ 4  7 13]
 [ 2 17  3]]


In [52]:
np.linalg.inv(arr1)

array([[-20. ,  15.5,  -0.5],
       [  1.4,  -1.1,   0.1],
       [  5.4,  -4.1,   0.1]])

In [53]:
arr1 = arr3

NameError: name 'arr3' is not defined

In [82]:
ar = np.array([[3,5],[4,7]])

In [83]:
arr = ar

In [84]:
arr

array([[3, 5],
       [4, 7]])

In [85]:
arr[0][1] = 0

In [86]:
arr

array([[3, 0],
       [4, 7]])

In [67]:
ar

array([[3, 0],
       [4, 7]])

In [68]:
ar

array([[3, 0],
       [4, 7]])

In [74]:
goa = ar.copy()
goa

array([[3, 0],
       [4, 7]])

In [75]:
goa[0][1] = 5

In [76]:
goa

array([[3, 5],
       [4, 7]])

In [77]:
ar

array([[3, 0],
       [4, 7]])