# Perform PCA Manually 

In [18]:
import pandas as pd
import numpy as np
from numpy.polynomial import Polynomial

from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler

In [8]:
data = load_iris()
df = pd.DataFrame(data=data.data, columns=data.feature_names)

In [11]:
# the data is already in scale in varient
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [20]:
df.corr()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.117570           0.871754   
sepal width (cm)           -0.117570          1.000000          -0.428440   
petal length (cm)           0.871754         -0.428440           1.000000   
petal width (cm)            0.817941         -0.366126           0.962865   

                   petal width (cm)  
sepal length (cm)          0.817941  
sepal width (cm)          -0.366126  
petal length (cm)          0.962865  
petal width (cm)           1.000000

In [21]:
df.var()

sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [23]:
cov_matrix = df.cov()
cov_matrix

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           0.685694         -0.042434           1.274315   
sepal width (cm)           -0.042434          0.189979          -0.329656   
petal length (cm)           1.274315         -0.329656           3.116278   
petal width (cm)            0.516271         -0.121639           1.295609   

                   petal width (cm)  
sepal length (cm)          0.516271  
sepal width (cm)          -0.121639  
petal length (cm)          1.295609  
petal width (cm)           0.581006

In [19]:
## lets caculate the mean roots of the solved equation
# X^2 - 5X - 6

p1 = Polynomial([-6,-5,1])
p1.roots()

array([-1.,  6.])

## Eigen Decomposition

In [24]:
# 1. Eigen Values
eigen_values = np.linalg.eigvals(cov_matrix)
eigen_values

array([4.22824171, 0.24267075, 0.0782095 , 0.02383509])

In [26]:
# 1. Eigen values 
# 2. Eigen vectores

eigen_values , eigen_vectors = np.linalg.eig(cov_matrix)

In [27]:
eigen_values

array([4.22824171, 0.24267075, 0.0782095 , 0.02383509])

In [28]:
eigen_vectors

array([[ 0.36138659, -0.65658877, -0.58202985,  0.31548719],
       [-0.08452251, -0.73016143,  0.59791083, -0.3197231 ],
       [ 0.85667061,  0.17337266,  0.07623608, -0.47983899],
       [ 0.3582892 ,  0.07548102,  0.54583143,  0.75365743]])

In [31]:
eigen_vectors[0] # 4.22

array([ 0.36138659, -0.65658877, -0.58202985,  0.31548719])

In [34]:
eigen_vectors[1] # 0.242

array([-0.08452251, -0.73016143,  0.59791083, -0.3197231 ])

In [35]:
eigen_vectors[2] # 0.078

array([ 0.85667061,  0.17337266,  0.07623608, -0.47983899])

In [37]:
eigen_vectors[3] # 0.023

array([0.3582892 , 0.07548102, 0.54583143, 0.75365743])

In [38]:
eigen_vectors.shape

(4, 4)