In [1]:
import numpy as np

In [3]:
np.full((3,3), fill_value=2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [12]:
ar = np.random.randint(1,5,size=(1,3))
print(ar)
print(np.where(ar > 2))

[[4 4 2]]
(array([0, 0], dtype=int64), array([0, 1], dtype=int64))


In [22]:
ar1 = np.linspace(1,5,num=10)
print(ar1)
ar2 = np.random.randint(1,6, size=(10))
print(ar2)
# np.size(ar1) == np.size(ar2)

np.append(ar1,ar2)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
[1 4 5 3 3 1 3 1 4 4]


array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ,
       1.        , 4.        , 5.        , 3.        , 3.        ,
       1.        , 3.        , 1.        , 4.        , 4.        ])

In [28]:
np.concatenate([[ar1,ar2]],axis=1)

array([[1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
        3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ],
       [1.        , 4.        , 5.        , 3.        , 3.        ,
        1.        , 3.        , 1.        , 4.        , 4.        ]])

In [32]:
print(ar1)
np.ceil(ar1)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


array([1., 2., 2., 3., 3., 4., 4., 5., 5., 5.])

In [33]:
np.floor(ar1)

array([1., 1., 1., 2., 2., 3., 3., 4., 4., 5.])

In [34]:
np.around(ar1)

array([1., 1., 2., 2., 3., 3., 4., 4., 5., 5.])

In [35]:
np.mean(ar1)

3.0

In [37]:
np.std(ar1)

1.2765694770084506

In [38]:
np.min(ar1)

1.0

In [39]:
np.max(ar1)

5.0

In [42]:
print(ar1)
np.argmax(ar1)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


9

In [41]:
np.argmin(ar1)

0

In [3]:
import datetime as dt

now = dt.datetime.now().date()
print(now)

2022-12-16


In [5]:
now.strftime("%Y %m %d")

'2022 12 16'

In [12]:
dt.date(2022, 3, 30).strftime("%d %m %Y")

'30 03 2022'

In [15]:
date = "20/02/2022"
date_format = "%d/%m/%Y"

dt.datetime.strptime(date, date_format)

datetime.datetime(2022, 2, 20, 0, 0)

In [24]:
for i in range(5):
    res = dt.datetime.now() + dt.timedelta(days=i,hours=i, seconds =i)
    print(res)

2022-12-16 21:41:33.377332
2022-12-17 22:41:34.377332
2022-12-18 23:41:35.377332
2022-12-20 00:41:36.377332
2022-12-21 01:41:37.377332
