# Numpy Functions

In [1]:
import numpy as np
import pandas as pd

# 1. reshape

In [2]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [6]:
arr.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# 2. np.nditer()

In [8]:
arr = np.array(
    [[1, 2, 3],
    [4, 5, 6]]
)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
for i in arr:
    print(i)

[1 2 3]
[4 5 6]


In [11]:
for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
6


In [12]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6


In [15]:
xyz = np.nditer(arr)
xyz

In [17]:
next(xyz)

array(1)

In [23]:
next(xyz)

StopIteration: 

# 3. np.ndenumerate()

In [24]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
for i,j in enumerate(arr):
    print(i,j)

0 [1 2 3]
1 [4 5 6]


In [27]:
for i,j in np.ndenumerate(arr):
    print(i,j)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


# 4. zeros()

In [29]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [30]:
arr = np.zeros(5,int)
arr

array([0, 0, 0, 0, 0])

In [31]:
arr = np.zeros((5,5),int)

In [32]:
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# 5. ones()

In [33]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [34]:
arr = np.ones(5,int)
arr

array([1, 1, 1, 1, 1])

In [35]:
arr = np.ones((5,5),int)
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# 6. arange()

In [36]:
range(1,11)

range(1, 11)

In [37]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [38]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
list(range(1,11,2))

[1, 3, 5, 7, 9]

In [40]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [41]:
arr = np.arange(10,0,-1)
arr

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [43]:
list(range(5,-1))

[]

In [44]:
arr = np.arange(5,-1)
arr

array([], dtype=int32)

# 7. linspace()
- Return evenly spaced values.
- syntax - np.linspace(start, end, num = 50)

In [45]:
arr = np.linspace(1,50,num=50)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [46]:
arr = np.linspace(1,50,num=10)
arr

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [47]:
6.44444444 - 1

5.44444444

In [48]:
11.88888889 - 6.44444444 

5.444444450000001

In [49]:
arr = np.linspace(1,50,num=10,retstep=True)
arr

(array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
        28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ]),
 5.444444444444445)

In [50]:
len(arr)

2

In [51]:
arr[0]

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [52]:
arr[1]

5.444444444444445

In [54]:
print(f"The evenly spaced array --> \n\n{arr[0]}\n\nThe Step size --> \n\n{arr[1]}")

The evenly spaced array --> 

[ 1.          6.44444444 11.88888889 17.33333333 22.77777778 28.22222222
 33.66666667 39.11111111 44.55555556 50.        ]

The Step size --> 

5.444444444444445


In [55]:
arr = np.linspace(1,100,num=10)
arr

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [56]:
23 - 12

11

In [57]:
45 - 34

11

In [58]:
arr = np.linspace(1,100,num=10,retstep=True)
arr

(array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.]), 11.0)

In [59]:
arr = np.linspace(1,101,num=10,retstep=True)
arr

(array([  1.        ,  12.11111111,  23.22222222,  34.33333333,
         45.44444444,  56.55555556,  67.66666667,  78.77777778,
         89.88888889, 101.        ]),
 11.11111111111111)

In [62]:
arr = np.linspace(1,50,num=50,retstep=True)
print(f"The evenly spaced array --> \n\n{arr[0]}\n\nThe Step size --> \n\n{arr[1]}")

The evenly spaced array --> 

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]

The Step size --> 

1.0


In [63]:
arr = np.linspace(1,100,num=50,retstep=True)
print(f"The evenly spaced array --> \n\n{arr[0]}\n\nThe Step size --> \n\n{arr[1]}")

The evenly spaced array --> 

[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]

The Step size --> 

2.020408163265306


# 8. eye()
- It will return an array with ones on diagonal and zeros elsewhere
- np.eye(shape,dtype)

In [64]:
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
arr = np.eye(3,5,dtype=int)
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [69]:
arr = np.eye(4,5,dtype=int)
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [70]:
arr = np.eye(4,15,dtype=int)
arr

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [71]:
arr = np.eye(10,15,dtype=int)
arr

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]])

# 9. identity()
- Identity matrix will be returned
- num of rows = num of col
- np.identity(value)

In [72]:
arr = np.identity(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [73]:
arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [75]:
arr = np.identity(10,dtype=int)
arr

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [76]:
arr = np.identity(10,15,dtype=int)
arr

TypeError: identity() got multiple values for argument 'dtype'

# 10. random()
- Used to generate random valued array
- 1. rand()
- 2. randint()
- 3. randn()
- 4. ranf()

# 10.1 rand()
- It will return values between 0 and 1

In [83]:
arr = np.random.rand(5)
arr

array([0.70662036, 0.29083391, 0.07911026, 0.2638923 , 0.62541975])

In [84]:
arr = np.random.rand(5,5)
arr

array([[0.91068714, 0.70638798, 0.33564853, 0.53712722, 0.87863657],
       [0.50664077, 0.66763539, 0.36329893, 0.02851461, 0.69025181],
       [0.60252103, 0.79689697, 0.44731368, 0.04963201, 0.74986037],
       [0.85583063, 0.8964125 , 0.30415859, 0.52741802, 0.03877611],
       [0.17304326, 0.97531104, 0.75938942, 0.46433589, 0.51663022]])

In [85]:
pd.DataFrame(arr)

0         1         2         3         4
0  0.910687  0.706388  0.335649  0.537127  0.878637
1  0.506641  0.667635  0.363299  0.028515  0.690252
2  0.602521  0.796897  0.447314  0.049632  0.749860
3  0.855831  0.896412  0.304159  0.527418  0.038776
4  0.173043  0.975311  0.759389  0.464336  0.516630

# 10.2 randint()

In [116]:
arr = np.random.randint(1,5)
arr

1

In [121]:
arr = np.random.randint(1,50)
arr

16

In [122]:
arr = np.random.randint(1,50,size=10)
arr

array([ 1,  6, 32, 13, 41, 16, 16, 47,  1,  3])

In [123]:
arr = np.random.randint(1,50,size=(10,10))
arr

array([[32, 33, 38,  3, 45, 20, 38,  3, 37, 23],
       [19, 41, 44, 34, 17, 14,  8, 35, 22, 28],
       [ 4, 27, 32, 20, 25, 33, 46, 28,  4, 14],
       [46, 31, 14, 29, 31, 14,  5,  8, 21, 12],
       [ 1, 30,  5,  5, 44, 37, 25, 26, 47, 22],
       [18, 20, 30, 20, 45, 28, 14, 21,  6, 21],
       [ 6, 47, 38, 47, 25, 38, 45, 40,  2, 26],
       [40, 30, 23, 46, 13, 32, 44, 21,  5, 43],
       [12, 33,  2, 40, 26, 29, 27, 20, 19, 15],
       [15, 34,  2, 10, 14, 29, 39, 12, 18, 39]])

# 10.3 randn()
- It will return values which are normally distributed
-  mean 0 and variance 1

In [124]:
arr = np.random.randn(10)
arr

array([ 1.7484523 , -1.25329241,  0.11526433, -0.77170597,  2.52643961,
        0.41435622, -0.69987495,  0.80114777,  1.50696898,  0.1456718 ])

In [127]:
arr = np.random.randn(10,10)
len(arr)

10

In [128]:
for i in arr:
    print(i)

[ 0.27337286  0.49846339 -0.5793975  -0.01437304  0.42609383  0.7383423
 -1.0137592  -0.38976288 -0.66097621  0.47037654]
[-0.84290267 -0.02204209  0.10332183  0.9205181   0.58056186 -2.22772144
 -2.08665879  1.19398718 -0.92216189 -1.05130436]
[-1.14577388  0.34027004  0.27228735 -1.91524332 -0.5887288  -0.88038854
  4.27161285  1.62045762 -0.52961367  0.05957269]
[ 1.28019736  1.18967575  0.7573765   0.91840409 -1.88685634 -1.37214491
  1.14411555 -1.19438394  1.40239959 -2.12790431]
[-1.02653273 -0.61601402  0.28298108 -0.09693379  0.63648018 -0.37913012
 -1.42195988 -1.10224869 -0.76450019 -1.78766972]
[ 1.11247253  0.58098065  2.27615723 -0.29537005  0.96613558  1.8353684
  1.04358909  0.23097024 -0.61762306 -0.2843022 ]
[ 0.11054599  0.16616532 -1.25145252 -0.11057973 -0.30877749  0.90991142
  0.25281952  0.18051106 -0.07263073 -0.01387216]
[-0.52968447  0.10083257 -1.38390912  0.69504361 -0.87250756  2.23569871
 -0.13799378 -0.18551003 -0.99808865  0.86205463]
[ 0.48558909 -0.98

In [129]:
arr

array([[ 0.27337286,  0.49846339, -0.5793975 , -0.01437304,  0.42609383,
         0.7383423 , -1.0137592 , -0.38976288, -0.66097621,  0.47037654],
       [-0.84290267, -0.02204209,  0.10332183,  0.9205181 ,  0.58056186,
        -2.22772144, -2.08665879,  1.19398718, -0.92216189, -1.05130436],
       [-1.14577388,  0.34027004,  0.27228735, -1.91524332, -0.5887288 ,
        -0.88038854,  4.27161285,  1.62045762, -0.52961367,  0.05957269],
       [ 1.28019736,  1.18967575,  0.7573765 ,  0.91840409, -1.88685634,
        -1.37214491,  1.14411555, -1.19438394,  1.40239959, -2.12790431],
       [-1.02653273, -0.61601402,  0.28298108, -0.09693379,  0.63648018,
        -0.37913012, -1.42195988, -1.10224869, -0.76450019, -1.78766972],
       [ 1.11247253,  0.58098065,  2.27615723, -0.29537005,  0.96613558,
         1.8353684 ,  1.04358909,  0.23097024, -0.61762306, -0.2843022 ],
       [ 0.11054599,  0.16616532, -1.25145252, -0.11057973, -0.30877749,
         0.90991142,  0.25281952,  0.18051106

# 10.4 ranf()
- Return values between 0 and 1

In [130]:
arr = np.random.ranf(5)
arr

array([0.74337986, 0.40281506, 0.45528621, 0.07453758, 0.60450386])

In [132]:
arr = np.random.ranf(10)
arr

array([0.15115822, 0.83667414, 0.14499166, 0.94973017, 0.77651254,
       0.5027672 , 0.3063766 , 0.69782234, 0.96189498, 0.48508073])

In [139]:
dict_np_functions = {
    "Zeros" : np.zeros(10,int),
    "Ones"  : np.ones(10,int),
    "Arange": np.arange(101,111),
    "Linspace": np.linspace(10,50,num=10),
    "Randint": np.random.randint(10,50,size = 10),
    "Randn" : np.random.randn(10)
}
dict_np_functions

{'Zeros': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 'Ones': array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 'Arange': array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110]),
 'Linspace': array([10.        , 14.44444444, 18.88888889, 23.33333333, 27.77777778,
        32.22222222, 36.66666667, 41.11111111, 45.55555556, 50.        ]),
 'Randint': array([30, 22, 39, 26, 30, 13, 10, 11, 16, 15]),
 'Randn': array([ 1.05350842,  1.24168949,  1.1093096 ,  1.27915906,  1.36617623,
        -0.0042346 , -1.77438726, -1.16951128, -0.22384205, -0.43985653])}

In [140]:
pd.DataFrame(dict_np_functions)

Zeros  Ones  Arange   Linspace  Randint     Randn
0      0     1     101  10.000000       30  1.053508
1      0     1     102  14.444444       22  1.241689
2      0     1     103  18.888889       39  1.109310
3      0     1     104  23.333333       26  1.279159
4      0     1     105  27.777778       30  1.366176
5      0     1     106  32.222222       13 -0.004235
6      0     1     107  36.666667       10 -1.774387
7      0     1     108  41.111111       11 -1.169511
8      0     1     109  45.555556       16 -0.223842
9      0     1     110  50.000000       15 -0.439857

# 11. sort()

In [141]:
arr = np.random.randint(1,10,size=5)
arr

array([9, 9, 4, 4, 3])

In [142]:
np.sort(arr)

array([3, 4, 4, 9, 9])

In [143]:
arr = np.random.randint(1,10,size=15)
arr

array([5, 9, 2, 5, 5, 3, 4, 1, 7, 6, 6, 5, 4, 2, 9])

In [144]:
np.sort(arr)

array([1, 2, 2, 3, 4, 4, 5, 5, 5, 5, 6, 6, 7, 9, 9])

In [149]:
arr = np.random.randint(1,50,size=(3,3))
arr

array([[31, 31,  4],
       [33, 45, 25],
       [ 1, 15, 39]])

In [150]:
np.sort(arr)

array([[ 4, 31, 31],
       [25, 33, 45],
       [ 1, 15, 39]])

In [153]:
np.sort(arr,axis=1) # Sort rows

array([[ 4, 31, 31],
       [25, 33, 45],
       [ 1, 15, 39]])

In [154]:
np.sort(arr,axis=0) # Sort your col

array([[ 1, 15,  4],
       [31, 31, 25],
       [33, 45, 39]])

# append()
- syntax :- np.append(array1,array2,axis=None)
- axis = 0 --> Rows
- axis = 1 --> Col

In [155]:
li = [1,2,3]
li.append(50)

In [156]:
li

[1, 2, 3, 50]

In [157]:
li.append([1,2,3])

In [158]:
li

[1, 2, 3, 50, [1, 2, 3]]

In [159]:
li.extend([11,22,33])
li

[1, 2, 3, 50, [1, 2, 3], 11, 22, 33]

In [160]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([11,22,33,44,55])
new_arr = np.append(arr1,arr2)
new_arr

array([ 1,  2,  3,  4,  5, 11, 22, 33, 44, 55])

In [162]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array(500)
new_arr = np.append(arr1,arr2)
new_arr

array([  1,   2,   3,   4,   5, 500])

In [163]:
arr1 = np.array([1,2,3,4,5])
# arr2 = np.array(500)
new_arr = np.append(arr1,5000)
new_arr

array([   1,    2,    3,    4,    5, 5000])

In [166]:
arr1 = np.array([[1,2,3,4,5]])
arr2 = np.array([[11,22,33,44,55]])
new_arr = np.append(arr1,arr2,axis=0)
new_arr

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [168]:
arr1 = np.array([[1,2,3,4,5]])
arr2 = np.array([[11,22,33,44,55]])
new_arr = np.append(arr1,arr2,axis=1)
new_arr

array([[ 1,  2,  3,  4,  5, 11, 22, 33, 44, 55]])

In [169]:
arr1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
arr2 = np.array([[11,22,33,44,55],[11,22,33,44,55]])
new_arr = np.append(arr1,arr2,axis=1)
new_arr

array([[ 1,  2,  3,  4,  5, 11, 22, 33, 44, 55],
       [ 1,  2,  3,  4,  5, 11, 22, 33, 44, 55]])

In [170]:
arr1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
arr2 = np.array([[11,22,33,44,55],[11,22,33,44,55]])
new_arr = np.append(arr1,arr2,axis=0)
new_arr

array([[ 1,  2,  3,  4,  5],
       [ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55],
       [11, 22, 33, 44, 55]])

array([[ 1,  2,  3,  4,  5],
       [ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55],
       [11, 22, 33, 44, 55]])

# np.concatenate

In [9]:
import numpy as np
arr1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
arr2 = np.array([[11,22,33,44,55],[11,22,33,44,55]])
np.concatenate([arr1, arr2],axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55],
       [11, 22, 33, 44, 55]])

In [10]:
arr1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
arr2 = np.array([[11,22,33,44,55],[11,22,33,44,55]])
np.concatenate([arr1, arr2],axis=1)

array([[ 1,  2,  3,  4,  5, 11, 22, 33, 44, 55],
       [ 1,  2,  3,  4,  5, 11, 22, 33, 44, 55]])