# Numpy-log

In [1]:
import numpy as np

#### Natural Log
- np.log()

In [2]:
np.log(10)

2.302585092994046

In [3]:
np.log(1)

0.0

In [4]:
np.log(0)

C:\Users\hp\AppData\Local\Temp\ipykernel_13068\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [5]:
np.log(2)

0.6931471805599453

In [6]:
np.log2(10)

3.321928094887362

In [7]:
np.log10(10)

1.0

In [8]:
np.log10(2)

0.3010299956639812

In [9]:
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [10]:
np.log(arr)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301])

In [11]:
np.log([1,2,3])

array([0.        , 0.69314718, 1.09861229])

In [12]:
np.log((1,2,3))

array([0.        , 0.69314718, 1.09861229])

In [13]:
np.log2(arr)

array([3.32192809, 4.32192809, 4.9068906 , 5.32192809, 5.64385619])

In [14]:
np.log10(arr)

array([1.        , 1.30103   , 1.47712125, 1.60205999, 1.69897   ])