# Nympy-Linear Algebra

In [1]:
import numpy as np

In [2]:
arr1 = np.array([[3,2],[4,6]])
print(f"Array1 --> \n{arr1}")
arr2 = np.array([15,30])
print(f"Array2 --> \n{arr2}")

Array1 --> 
[[3 2]
 [4 6]]
Array2 --> 
[15 30]


In [3]:
res = np.linalg.solve(arr1,arr2)
print(f"Result --> {res}")

Result --> [3. 3.]


In [ ]:
3x + 5y + 10z = 20
4x + 7y + 13z = 30
2x + 17y + 3z = 40

In [4]:
arr1 = np.array([[3,5,10],[4,7,13],[2,17,3]])
print(f"Array1 --> \n{arr1}")
arr2 = np.array([20,30,40])
print(f"Array2 --> \n{arr2}")

Array1 --> 
[[ 3  5 10]
 [ 4  7 13]
 [ 2 17  3]]
Array2 --> 
[20 30 40]


In [5]:
res = np.linalg.solve(arr1,arr2)
print(f"Result --> {res}")

Result --> [ 45.  -1. -11.]


In [6]:
x = 45
y = -1
z = -11

In [7]:
3*x + 5*y + 10*z

20

In [8]:
4*x + 7*y + 13*z

30

In [9]:
2*x + 17*y + 3*z

40

# Inverse of matrix

In [10]:
[
    [1,2],
    [3,4]
]

[[1, 2], [3, 4]]

In [12]:
array1 = np.array([
    [1,2],
    [3,4]
])
array1

array([[1, 2],
       [3, 4]])

In [14]:
np.linalg.inv(array1)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# Copy of an array

In [15]:
arr1 

array([[ 3,  5, 10],
       [ 4,  7, 13],
       [ 2, 17,  3]])

In [16]:
arr2 = arr1

In [17]:
arr2

array([[ 3,  5, 10],
       [ 4,  7, 13],
       [ 2, 17,  3]])

In [18]:
arr2[0][1] = 500

In [19]:
arr1

array([[  3, 500,  10],
       [  4,   7,  13],
       [  2,  17,   3]])

In [20]:
arr2 = arr1.copy()

In [21]:
arr2

array([[  3, 500,  10],
       [  4,   7,  13],
       [  2,  17,   3]])

In [22]:
arr2[0][1] = 5

In [23]:
arr1

array([[  3, 500,  10],
       [  4,   7,  13],
       [  2,  17,   3]])

In [24]:
arr2

array([[ 3,  5, 10],
       [ 4,  7, 13],
       [ 2, 17,  3]])