### Why numpy array is faster than python list
- practical representation of numpy 

In [ ]:
import numpy as np
import time

In [9]:
num = 100000000
list1 = range(num)
list2 = range(num)
multi = []

In [12]:
p_start_time = time.time()
for i in range(len(list1)):
    multi.append(list1[i]*list2[i])
p_end_time = time.time()
print(f"Time taken by python list multiplication: {p_end_time - p_start_time}")

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
print("<>"*50)
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

a1 = np.array(num)
a2 = np.array(num)
Np_start_time = time.time()
r = a1*a2
Np_end_time = time.time()
print(f"Time taken by Numpy list multiplication: {Np_end_time - Np_start_time}")

Time taken by python list multiplication: 40.00646734237671
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Time taken by Numpy list multiplication: 0.011702537536621094


In [1]:
import numpy as np
import pandas as pd

In [5]:
x = np.array([1,2,3,4,5])
y = np.array([10,20,30,40,50])
data = {"Col1":x, 'Col2':y}
table = pd.DataFrame(data)
print(table)

   Col1  Col2
0     1    10
1     2    20
2     3    30
3     4    40
4     5    50


In [6]:
x = np.array([1,2,3,4,5,6])
y = np.array([10,20,30,40,50])
data = {"Col1":x, 'Col2':y}
table = pd.DataFrame(data)
print(table)

ValueError: All arrays must be of the same length

In [7]:
x = np.array([1,2,3,4,5,6])
y = np.array([10,20,30,40,50,"x"])
data = {"Col1":x, 'Col2':y}
table = pd.DataFrame(data)
print(table)

   Col1 Col2
0     1   10
1     2   20
2     3   30
3     4   40
4     5   50
5     6    x


## numpy can strore only one datatype value

In [2]:
import numpy as np
import pandas as pd

In [3]:
li1 = [1,2,3,4.5,6.3,"python",1+5j]
li1

[1, 2, 3, 4.5, 6.3, 'python', (1+5j)]

In [4]:
n_list = np.array([1,2,3,4,5])
n_list

array([1, 2, 3, 4, 5])

In [5]:
n_list2 = np.array(['1','2','3','4','5'])
n_list2

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [6]:
n_list3 = np.array([1+1j, 1+2j, 1+3j, 1+4j, 1+5j])
n_list3

array([1.+1.j, 1.+2.j, 1.+3.j, 1.+4.j, 1.+5.j])

In [7]:
n_list4 = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
n_list4

array([1.1, 1.2, 1.3, 1.4, 1.5])

## Trying to add different datatypes in np array

In [8]:
n_list = np.array([1,2,3,4,5,6.5])
print(n_list)
type(n_list)

[1.  2.  3.  4.  5.  6.5]


numpy.ndarray

In [10]:
n_list11 = np.array([1,2,6.5,3,4,5])
n_list11

array([1. , 2. , 6.5, 3. , 4. , 5. ])

In [12]:
n_list12 = np.array([1, 2, 6.5, 3, 4, 5, "python"])
n_list12

array(['1', '2', '6.5', '3', '4', '5', 'python'], dtype='<U32')

In [13]:
n_list13 = np.array([1, 2, 6.5, 3, 4, 5, "python", 1 + 5j])
n_list13

array(['1', '2', '6.5', '3', '4', '5', 'python', '(1+5j)'], dtype='<U64')

In [15]:
n_list13 = np.array([1, 2, 6.5, 3, 4, 5, 1+5j])
n_list13

array([1. +0.j, 2. +0.j, 6.5+0.j, 3. +0.j, 4. +0.j, 5. +0.j, 1. +5.j])

In [25]:
dir("ndarray")

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',


In [26]:
dir("numpy")

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',


In [20]:
dir(list())

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [1]:
import numpy as np

In [2]:
x = np.array([1+5j, 1+2j, 6+4j, 5])
x

array([1.+5.j, 1.+2.j, 6.+4.j, 5.+0.j])

In [3]:
y = np.array([1,2,3,4,5.5])
y

array([1. , 2. , 3. , 4. , 5.5])

In [4]:
g = np.array([1.1, 2.2, 3.5, 5])
g

array([1.1, 2.2, 3.5, 5. ])

In [6]:
h = np.array([1, 2, 3, 5+4j])
h

array([1.+0.j, 2.+0.j, 3.+0.j, 5.+4.j])

In [7]:
v = np.array([1, 2, 3, 5+4j, "a"])
v

array(['1', '2', '3', '(5+4j)', 'a'], dtype='<U64')

In [8]:
v1 = np.array([1, 2, 3, 5+4j, "a", 2.3])
v1

array(['1', '2', '3', '(5+4j)', 'a', '2.3'], dtype='<U64')

In [10]:
v1s = np.array([1.1, 2.2, 3.5, 5+4j, "a", 2])
v1s

array(['1.1', '2.2', '3.5', '(5+4j)', 'a', '2'], dtype='<U64')

In [12]:
v1s = np.array([1.1, 2.2, 3.5, 5+4j, "a", 2],dtype=str)
v1s

array(['1.1', '2.2', '3.5', '(5+4j)', 'a', '2'], dtype='<U6')

In [13]:
array = np.array([1,2,3,4,5,6.5,7.5,8.5],dtype=int)
array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
array1 = np.array([1,2,3,4,5,6.5,7.5,8.5],dtype=float)
array1

array([1. , 2. , 3. , 4. , 5. , 6.5, 7.5, 8.5])

In [15]:
array1 = np.array([1,2,3,4,5,6.5,7.5,8.5],dtype=complex)
array1

array([1. +0.j, 2. +0.j, 3. +0.j, 4. +0.j, 5. +0.j, 6.5+0.j, 7.5+0.j,
       8.5+0.j])

In [16]:
array12 = np.array([1,2,3,4,5,6.5,7.5,8.5],dtype=str)
array12

array(['1', '2', '3', '4', '5', '6.5', '7.5', '8.5'], dtype='<U3')

In [ ]:
import random

In [23]:
a = np.array(random.random(1,20))
b = np.array(random.random(1,20))
a3 = np.append(a,b)
print(a3)

NameError: name 'random' is not defined

In [24]:
a4 = np.floor(a,b)
print(a4)

TypeError: ufunc 'floor' output (typecode 'd') could not be coerced to provided output parameter (typecode 'l') according to the casting rule ''same_kind''

In [25]:
[1,2,3,4] % 2

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [26]:
ar = np.array([1,2,3,4])
ar / 2

array([0.5, 1. , 1.5, 2. ])

In [60]:
import random
n = random.random()
n

0.024881028400628336

In [76]:
n2 = random.randint(1,10)
n2

3

In [77]:
np_ = np.array([1,2,3,4,5])
np_ * 5

array([ 5, 10, 15, 20, 25])

In [78]:
np_ = np.array([1,2,3,4,5])
np_ + 5

array([ 6,  7,  8,  9, 10])

In [79]:
np_ = np.array([1,2,3,4,5])
np_ // 5

array([0, 0, 0, 0, 1], dtype=int32)

In [82]:
np_ = np.array([1111,222,32,400,5+77j])
np_ // 5

array([222.+0.j,  44.+0.j,   6.+0.j,  80.+0.j,   1.+0.j])

In [83]:
import numpy as np

In [130]:
arr = np.array([[1,2,3], 
                [4,5,6],[7,8,9]])


print(f"Type of array: {type(arr)}")
print(f"what dimension of array: {arr.ndim}")
print(f"what shape of array: {arr.shape}")
print("Size of array: ", arr.size)
print("Array stores elements of type: ", arr.dtype)


TypeError: unhashable type: 'list'

In [126]:
arr = np.array([[1,2,3], 
                [4,5,6],8,9,10],dtype=list)


print(f"Type of array: {type(arr)}")
print(f"what dimension of array: {arr.ndim}")

Type of array: <class 'numpy.ndarray'>
what dimension of array: 1


In [127]:
arr = np.array([[1,2,3], 
                [4,5,6],[7,8,9,10]])


print(f"Type of array: {type(arr)}")
print(f"what dimension of array: {arr.ndim}")
print(f"what shape of array: {arr.shape}")

Type of array: <class 'numpy.ndarray'>
what dimension of array: 1
what shape of array: (3,)


C:\Users\yashd\AppData\Local\Temp\ipykernel_6840\2318095276.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[1,2,3],


In [128]:
arr = np.array([[1,2,3], 
                [4,5,6],[7,8,9,10]],dtype=object)


print(f"Type of array: {type(arr)}")
print(f"what dimension of array: {arr.ndim}")
print(f"what shape of array: {arr.shape}")

Type of array: <class 'numpy.ndarray'>
what dimension of array: 1
what shape of array: (3,)


In [129]:
arr = np.array([[1,2,3], 
                [4,5,6],[7,8,9], 44],dtype=object)


print(f"Type of array: {type(arr)}")
print(f"what dimension of array: {arr.ndim}")
print(f"what shape of array: {arr.shape}")
print("Size of array: ", arr.size)
print("Array stores elements of type: ", arr.dtype)
 

Type of array: <class 'numpy.ndarray'>
what dimension of array: 1
what shape of array: (4,)
Size of array:  4
Array stores elements of type:  object


In [137]:
arr = np.array((1,2,3,4,5,6,7,8,9))

print(f"arr = {arr}")
print(f"Type of array: {type(arr)}")
print(f"what dimension of array: {arr.ndim}")
print(f"what shape of array: {arr.shape}")
print("Size of array: ", arr.size)
print("Array stores elements of type: ", arr.dtype)

arr = [1 2 3 4 5 6 7 8 9]
Type of array: <class 'numpy.ndarray'>
what dimension of array: 1
what shape of array: (9,)
Size of array:  9
Array stores elements of type:  int32


In [143]:
arr = np.array({1,2,3,4,5,6,7,8,9})

print(f"arr = {arr}")
print(f"Type of array: {type(arr)}")
print(f"what dimension of array: {arr.ndim}")
print(f"what shape of array: {arr.shape}")
print("Size of array: ", arr.size)
print("Array stores elements of type: ", arr.dtype)

arr = {1, 2, 3, 4, 5, 6, 7, 8, 9}
Type of array: <class 'numpy.ndarray'>
what dimension of array: 0
what shape of array: ()
Size of array:  1
Array stores elements of type:  object


In [139]:
arr = np.array({1:2, 3:4, 5:6, 7:8, 9:10})

print(f"arr = {arr}")
print(f"Type of array: {type(arr)}")
print(f"what dimension of array: {arr.ndim}")
print(f"what shape of array: {arr.shape}")
print("Size of array: ", arr.size)
print("Array stores elements of type: ", arr.dtype)

arr = {1: 2, 3: 4, 5: 6, 7: 8, 9: 10}
Type of array: <class 'numpy.ndarray'>
what dimension of array: 0
what shape of array: ()
Size of array:  1
Array stores elements of type:  object
