In [1]:
import numpy as np

In [2]:
f_arr = np.floor([1.1, 2.5, 3.6, 8.5, 4.5])
f_arr

array([1., 2., 3., 8., 4.])

In [3]:
f_ceil = np.ceil([1.1, 2.5, 3.6, 8.5, 4.5])
f_ceil

array([2., 3., 4., 9., 5.])

### changing datatypes of np.array

In [4]:
li = [1,2,3,4,5]
float_list = [float(x) for x in li ]
print(float_list)

[1.0, 2.0, 3.0, 4.0, 5.0]


In [5]:
float(li)

TypeError: float() argument must be a string or a number, not 'list'

In [12]:
import numpy as np

f_ar = np.array([1,2,3,4,5,2.5])
print(f_ar)
print(type(f_ar))
print(f_ar.astype(float))

[1.  2.  3.  4.  5.  2.5]
<class 'numpy.ndarray'>
[1.  2.  3.  4.  5.  2.5]


In [7]:
f_ar.dtype

dtype('float64')

In [8]:
int_arr = np.array([1.5,2.6,3.7,4.2,5])

int_arr

array([1.5, 2.6, 3.7, 4.2, 5. ])

In [11]:
int_arr.astype(int)

array([1, 2, 3, 4, 5])

In [17]:
arr = np.array([1,2,3,4,6,7,8,9])
arr[0][2]

IndexError: invalid index to scalar variable.

In [27]:
arr = np.array([[1,2,3,4,6,7,8,9]])
arr[0,2]

3

In [30]:
arr = np.array([1,2,3,4,6,7,8,9])
# arr[0]
arr[-1]

9

In [33]:
add_ele = arr[2] + arr[3]
add_ele

7

In [42]:
multi_ele = arr[5] * arr[-1]
print(multi_ele)

63


## Accecing array from 2-dimentional array

In [49]:
arr = np.array([[1,2,3,4,5], 
                [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
print('1st element on 2st row: ', arr[1, 0])
print('last element on 2st row: ', arr[1, -1])
print('last array: ', arr[-1])
print('1st array: ', arr[0])

2nd element on 1st row:  2
1st element on 2st row:  6
last element on 2st row:  10
last array:  [ 6  7  8  9 10]
1st array:  [1 2 3 4 5]


### Accesing Three Dimentional arrays 

In [66]:
arr_list = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])

arr_list[0][0,1]

2

In [74]:
arr_list = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])
print(arr_list[0,0][0])
print(arr_list[0,1][0])
print(arr_list[0,1][2])

1
4
6


### proof of ho numpy is faster than python list

In [79]:
import numpy as np
import time

num = 1000000
lis3 = []

list1 = range(num)
list2 = range(num)

start_time  = time.time()
for i in range(len(list1)):
    lis3.append(list1[i] * list2[i])
    
end_time = time.time()
print(f"time taken by python list: {end_time - start_time}")

print("-"*50)


a1 = np.array(num)
a2 = np.array(num)

np_start_time = time.time()
r = a1 * a2
np_end_time = time.time()
print(f"time taken by numpy array: {np_end_time - np_start_time}")

time taken by python list: 0.3510873317718506
--------------------------------------------------
time taken by numpy array: 0.0


In [108]:
int_arr = np.array([1.5,2.6,3.7,4.2,5],dtype =int)

int_arr.dtype
print(int_arr)

[1 2 3 4 5]


In [96]:
int_arr.astype(int)

array([1, 2, 3, 4, 5])

In [109]:
int_arr = np.array((1.5,2.6,3.7,4.2,5),dtype =int)

int_arr.dtype
print(int_arr)

[1 2 3 4 5]


In [114]:
int_arr = np.array({1.5,2.6,3.7,4.2,5})
print(int_arr.dtype)
print(int_arr)

object
{1.5, 2.6, 3.7, 4.2, 5}
