## 1. numpy.ceil()
- it will return a incremented value 
- 3.1 --> 4.0
- 3.5 --> 4.0
- 4.9 --> 5.0
- 5.5 --> 6.0

In [2]:
import numpy as np

ceil_arr = np.ceil(np.array([1.1,2.5,3.6,9.4,7.5]))
print(ceil_arr)

[ 2.  3.  4. 10.  8.]


In [4]:
ar1 = np.array([1.1,2.5,3.6,9.4,7.5])

nw_ar = np.ceil(ar1)
print(nw_ar)

[ 2.  3.  4. 10.  8.]


## np.floor()
- it returns smaller value than current value 
- it's only ignores decimal point numbers and returns intiger number 

- 3.1 = 3
- 5.9 = 5
- 9.9 = 9

In [9]:
5 // 2

2

In [10]:
5 / 2

2.5

In [11]:
7/2

3.5

In [12]:
7//2

3

In [14]:
np.floor([1.5, 3.9, 6.9, 4.6])

array([1., 3., 6., 4.])

In [15]:
np.floor([5.5,6.6,8.8,9.9,7.7])

array([5., 6., 8., 9., 7.])

## np.around()
- it returns the round of numbers
- it is similar to python inbuild round funcion

In [18]:
n = round(1.5698)
n

2

In [19]:
n = round(1.5698,2)
n

1.57

In [25]:
n2 = round(1.779635412,4)
n2

1.7796

In [27]:
rounded_num = np.around([1.45693, 2.58963, 7.8963211, 9.56644823], 2)
rounded_num

array([1.46, 2.59, 7.9 , 9.57])

In [28]:
rounded_num = np.around([1.45693, 2.58963, 7.8963211, 9.56644823])
rounded_num

array([ 1.,  3.,  8., 10.])

## np.where(arr,condition)
- it returns the indices of the satisfied conditions from within a array

In [36]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

even_index = np.where(arr % 2 == 0)
print(f"Even num Array indices: {even_index}")

odd_index = np.where(arr % 2)
print(f"odd num Array indices: {odd_index}")

Even num Array indices: (array([1, 3, 5, 7, 9], dtype=int64),)
odd num Array indices: (array([0, 2, 4, 6, 8], dtype=int64),)


In [42]:
strn  = "Machine Learning Is Amazing"

stn_array = np.array(list(strn.lower()))
arr_indices = np.where(stn_array == "a")
print(arr_indices)

(array([ 1, 10, 20, 22], dtype=int64),)


In [46]:
stn_array = np.array(list(strn.lower()))

arr_indices = np.where(stn_array == "a")
arr_indices[0].tolist()

[1, 10, 20, 22]

In [57]:
arr_indices = np.where(stn_array == "a")
arr_indices[0][1]
arr_indices[0][3]

22

In [58]:
arr_indices[0].tolist()

[1, 10, 20, 22]

In [59]:
for i in arr_indices[0]:
    print(i)

1
10
20
22


In [64]:
chars = list(strn.lower())

for i, j in enumerate(chars):
    if j == 'a':
        print(i)

1
10
20
22
