## 1. Arethmatics 

In [1]:
import numpy as np

In [2]:
nums = np.random.randint(low=10,high=50,size=5)
nums

array([45, 25, 23, 22, 42])

In [16]:
nums + 10

array([21, 34, 50, 35, 29])

In [3]:
nums - 5

array([40, 20, 18, 17, 37])

In [5]:
nums * 5

array([225, 125, 115, 110, 210])

In [6]:
nums / 5

array([9. , 5. , 4.6, 4.4, 8.4])

In [7]:
nums // 5

array([9, 5, 4, 4, 8], dtype=int32)

In [8]:
nums % 2

array([1, 1, 1, 0, 0], dtype=int32)

In [9]:
nums ** 2

array([2025,  625,  529,  484, 1764], dtype=int32)

In [10]:
nums ** 3

array([91125, 15625, 12167, 10648, 74088], dtype=int32)

In [11]:
np.floor(nums)

array([45., 25., 23., 22., 42.])

In [12]:
np.ceil(nums)

array([45., 25., 23., 22., 42.])

## np.add()

In [15]:
np.add(nums,nums)

array([90, 50, 46, 44, 84])

In [22]:
arr1 = np.array([[9,8],[2,4]])
print(arr)
print()
arr2 = np.array([[10,20], [30,40]])
print(arr2)

[[9 8]
 [2 4]]

[[10 20]
 [30 40]]


In [24]:
add = np.add(arr1,arr2)
print(add)

[[19 28]
 [32 44]]


In [42]:
arr1

array([[9, 8],
       [2, 4]])

In [28]:
arr2

array([[10, 20],
       [30, 40]])

In [105]:
arr1 

array([[9, 8],
       [2, 4]])

In [108]:
arr3 = np.array([[10,20], [40,50], [60,70]])

np.add(arr1,arr3)

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

### create a matrix additon without using np.add(arr1, arr2) function

In [84]:
a1 = [i.tolist() for i in np.nditer(arr1)]   ##  append values of arr1 to a1

a2 = [j.tolist() for j in np.nditer(arr2)]   ##  append values of arr1 to a2

add_a1_a2 = [a1[i] + a2[i] for i,j in enumerate(a1)]   ##  append additon of arr1 to arr2 to add_a1_a2

print(add_a1_a2)
print()

matrix = np.reshape(np.array(add_a1_a2),[2,2])        ## reshape to 2,2 matrix
print(f"matrix:\n\n{matrix}")


[19, 28, 32, 44]

matrix:

[[19 28]
 [32 44]]


### np.subtract

In [26]:
sub = np.subtract(arr1,arr2)
print(sub)

[[ -1 -12]
 [-28 -36]]


In [89]:
a1 = [i.tolist() for i in np.nditer(arr1)]   ##  append values of arr1 to a1

a2 = [j.tolist() for j in np.nditer(arr2)]   ##  append values of arr1 to a2

sub_a1_a2 = [a1[i] - a2[i] for i,j in enumerate(a1)]   ##  append suntraction of arr1 to arr2 to sub_a1_a2

matrix = np.reshape(np.array(sub_a1_a2),[2,2])        ## reshape to 2,2 matrix
print(f"matrix:\n\n{matrix}")

matrix:

[[ -1 -12]
 [-28 -36]]


## matrix Multiplication

In [90]:
arr1

array([[9, 8],
       [2, 4]])

In [91]:
arr2

array([[10, 20],
       [30, 40]])

In [93]:
multi = np.multiply(arr1, arr2)
print(multi)

[[ 90 160]
 [ 60 160]]


In [104]:
m1 = [int(i) for i in np.nditer(arr1)]
m2 = [int(i) for i in np.nditer(arr2)]

multiply = [m1[i] * m2[i] for i, j in enumerate(m1)]

print(multiply)

multi_shape = np.reshape(multiply,[2,2])
print(f"matrix is :\n\n{multi_shape}")

[90, 160, 60, 160]
matrix is :

[[ 90 160]
 [ 60 160]]


In [110]:
arr1

array([[9, 8],
       [2, 4]])

In [111]:
arr2

array([[10, 20],
       [30, 40]])

In [109]:
np.divide(arr1,arr2)

array([[0.9       , 0.4       ],
       [0.06666667, 0.1       ]])

In [112]:
9/10

0.9

In [114]:
8/20

0.4

In [115]:
2 / 30

0.06666666666666667

In [116]:
4/40

0.1

In [117]:
arr1

array([[9, 8],
       [2, 4]])

In [118]:
arr2

array([[10, 20],
       [30, 40]])

In [119]:
product = np.dot(arr1,arr2)

print(product)

[[330 500]
 [140 200]]


In [120]:
product

array([[330, 500],
       [140, 200]])

In [127]:
arr1 = np.array([[9,8],[2,4]])
print(arr1)
print()
arr2 = np.array([[10,20], [30,40]])
print(arr2)

[[9 8]
 [2 4]]

[[10 20]
 [30 40]]


In [180]:
r1 = arr1[0].tolist()
r2 = arr1[1].tolist()

R = r1+r2

print(R)

[9, 8, 2, 4]


In [192]:
C = []
c1 = arr2[0:,0]
c2 = arr2[0:,1]

C1 = [i for i in c1]
C2 = [i for i in c2]

C = C1 + C2

print(C)
print(R)

[10, 30, 20, 40]
[9, 8, 2, 4]


In [199]:
col1 = C[:2] 
col2 = C[2:]

row1 = R[:2]
row2 = R[2:]

print(col1)
print(col2)
print()
print(row1)
print(row2)

[10, 30]
[20, 40]

[9, 8]
[2, 4]


In [210]:
for i in range(len(row1)):
    print(row1[i]*col1[i])

90
240
