In [1]:
import numpy as np

In [8]:
num = np.around(1.7955333,3)
num

1.796

In [10]:
num = np.around(1.4333,2)
num

1.43

## np.where()

In [12]:
arr = np.arange(1,11)
print(arr)
np.where(arr % 2 == 0)

[ 1  2  3  4  5  6  7  8  9 10]


(array([1, 3, 5, 7, 9], dtype=int64),)

In [16]:
str1 = "Machine Learning and data science"

arr = np.array(list(str1.lower()))
print(arr)
arr1 = np.where(arr == "a")[0].tolist()
print(arr1)

['m' 'a' 'c' 'h' 'i' 'n' 'e' ' ' 'l' 'e' 'a' 'r' 'n' 'i' 'n' 'g' ' ' 'a'
 'n' 'd' ' ' 'd' 'a' 't' 'a' ' ' 's' 'c' 'i' 'e' 'n' 'c' 'e']
[1, 10, 17, 22, 24]


In [17]:
p_list = [1, 10, 17, 22, 24]

p_list + 1

TypeError: can only concatenate list (not "int") to list

## np.add()

In [46]:
arr1 = np.array([[7,8], [9,6]])

arr2 = np.array([[10,20], [30,40]])

add = arr1 + arr2
print(add)

[[17 28]
 [39 46]]


In [47]:
addition = np.add(arr1, arr2)
addition

array([[17, 28],
       [39, 46]])

In [48]:
sub = np.subtract(arr1, arr2)
sub

array([[ -3, -12],
       [-21, -34]])

In [49]:
multi = np.multiply(arr1, arr2)
print(multi)

[[ 70 160]
 [270 240]]


In [50]:
div = np.divide(arr1, arr2)
div

array([[0.7 , 0.4 ],
       [0.3 , 0.15]])

In [51]:
arr1

array([[7, 8],
       [9, 6]])

In [52]:
arr2

array([[10, 20],
       [30, 40]])

In [53]:
product_matrix = np.dot(arr1, arr2)
print(product_matrix)

[[310 460]
 [270 420]]


In [56]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a,"\n")
print(b)
pro = np.dot(a,b)
pro

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]]


array([[19, 22],
       [43, 50]])

In [61]:
def mydot(arr1, arr2):
     return sum([x*y for x,y in zip(arr1, arr2)])

def matmulvec(M, v):
    pro_mat = [mydot(r,v) for r in M]
    return np.reshape(pro_mat,[2,2])

matmulvec(arr1,arr2)

array([[310, 460],
       [270, 420]])

In [62]:
matmulvec(a,b)

array([[19, 22],
       [43, 50]])

In [65]:
print(arr1)
print()
print(arr2)

[[7 8]
 [9 6]]

[[10 20]
 [30 40]]


In [72]:
l = list(zip(arr1, arr2))
print(l)

[(array([7, 8]), array([10, 20])), (array([9, 6]), array([30, 40]))]


In [71]:
for x,y in l:
    print(sum(x*y))

230
510


## Trignometry

In [82]:
PI = np.pi
print(PI)

3.141592653589793


In [77]:
# 30
# Pi / 3
180/60

3.0

In [80]:
# 
180/30

6.0

In [81]:
180/45

4.0

In [88]:
# 360
PI * 2

6.283185307179586

In [89]:
np.sin(PI/2)

1.0

In [91]:
1/np.sqrt(2)

0.7071067811865475

In [93]:
1/np.sqrt(3)

0.5773502691896258

In [94]:
np.sqrt(3)

1.7320508075688772

In [100]:
from scipy import stats
v = np.arange(8,15)
print(v)
s = stats.mode(v)
s

[ 8  9 10 11 12 13 14]


ModeResult(mode=array([8]), count=array([1]))

In [102]:
s[0][0]

8

In [103]:
s[1]

array([1])

In [104]:
s[1][0]

1

In [112]:
np.full(2,1)

array([1, 1])

In [113]:
b = np.array(100)

print(b.shape)

()


In [115]:
b = np.array([100,200])

print(b.shape)

(2,)
