# Data Science
- 1. pandas :- Used for EDA(Exploratory Data Analysis),Data Preprocessing
- 2. numpy  :- Used for Numerical Computing
- 3. scikit-learn :- (Machine Learning Algorithm) = (sklearn)
- 4. seaborn :- For data visualization
- 5. matplotlib :- For data visualization
- 6. tensorflow :- Used for Deep Learning
- 7. nltk :- NLP
- 8. statsmodel 
- 9. scipy

In [1]:
import pandas as pd

In [3]:
d1 = {"Col1":[1,2,3,4,5],"Col2":[10,20,30,40,50]}
df = pd.DataFrame(d1)
df

Col1  Col2
0     1    10
1     2    20
2     3    30
3     4    40
4     5    50

In [4]:
d1 = {"Col1":[1,2,3,4,5,6],"Col2":[10,20,30,40,50]}
df = pd.DataFrame(d1)
df

ValueError: All arrays must be of the same length

In [5]:
import numpy as np

In [6]:
a1 = np.array([1,2,3])
a2 = np.array([10,20,30])
d1 = {"Col1":a1,"Col2":a2}
df = pd.DataFrame(d1)
df

Col1  Col2
0     1    10
1     2    20
2     3    30

In [7]:
a1 = np.array([1,2,3])
a2 = np.array([10,20,30])
a1 * a2

array([10, 40, 90])

In [8]:
a3 = np.append(a1,a2)
a3

array([ 1,  2,  3, 10, 20, 30])

In [10]:
np.floor([3.7,5.5,6.7,3.2,9.9,9.2])

array([3., 5., 6., 3., 9., 9.])

In [11]:
np.ceil([3.7,5.5,6.7,3.2,9.9,9.2])

array([ 4.,  6.,  7.,  4., 10., 10.])

In [12]:
np.where(np.array([1,1,1,2,3,4,5]) > 1)

(array([3, 4, 5, 6], dtype=int64),)

In [17]:
np.where(np.array([1,1,1,2,3,4,5]) == 1)[0].tolist()

[0, 1, 2]

In [18]:
np.array([1,1,1,2,3,4,5]) / 2

array([0.5, 0.5, 0.5, 1. , 1.5, 2. , 2.5])

In [19]:
np.pi / 6

0.5235987755982988